### ISSUE TITLE
Pixel 3i

### ISSUE THREAD

**Issue by Marcof64** [ultralytics/hub#23] opened 2022-04-27 06:51 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

Does not load downloaded data sets and does not start recognition

**Comment by sergiossm** [comment] 2022-04-27 17:22
Hi @Marcof64, thank you for using our product!

I assume your issue is related to the app as you're mentioning the recognition. Could you provide further info on how to replicate the issue? 

The app currently doesn't have support for Datasets, maybe you're referring to a Project or a Model? If that's the case, what's its name? And is it public or private?

Also, can you confirm that the device you're using is a Google Pixel 3?

**Comment by Marcof64** [comment] 2022-04-28 07:41
Hello Sergio,

 

Yes I am trying the public Android app.

 

My company, COMM3000 srp, has bought a license for the Ultralytics library and developing on iOS, all works fine there.

 

I installed the Android app on my Pixel 3i to try it out on Android, registered and downloaded the public Yolo models available.

 

When I start “recognition” nothing happens, when I change model, even the smallest one and then try recognition the phone says something like “loading model” and never leaves that message.

 

I understand Android phones have all types of different HW and so the app may not work on many phones, is the Pixel 3i supported? Do you have a list of supported Android phones supported or Android chipsets supported?

 

Thanks

 

Marco

+39 335 22 9696

 

Da: Sergio Sánchez ***@***.***> 
Inviato: mercoledì 27 aprile 2022 19:22
A: ultralytics/hub ***@***.***>
Cc: Marcof64 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [ultralytics/hub] Pixel 3i (Issue #23)

 

Hi @Marcof64 <https://github.com/Marcof64> , thank you for using our product!

I assume your issue is related to the app as you're mentioning the recognition. Could you provide further info on how to replicate the issue?

The app currently doesn't have support for Datasets, maybe you're referring to a Project or a Model? If that's the case, what's its name? And is it public or private?

Also, can you confirm that the device you're using is a Google Pixel 3?

**Comment by sergiossm** [comment] 2022-04-28 11:41
@Marcof64 thank you for your understanding 🙌

As you say, the great HW difference in Android devices makes it a bit tricky to develop this kind of app. Even though we try our best!

> Do you have a list of supported Android phones supported or Android chipsets supported? >

We currently don't have a list of supported/unsupported Android devices. Right now we're conducting all our tests on a Xiaomi Mi 11.

> When I start “recognition” nothing happens, when I change model, even the smallest one and then try recognition the phone says something like “loading model” and never leaves that message. >
We've implemented a fix for this, but we, unfortunately, couldn't test it as we're not able to reproduce the bug.

The update (v0.1.1+22) is now being reviewed by the Google Play team, I'll let you know when it's approved! 🔔

**Comment by sergiossm** [comment] 2022-04-28 14:36
@Marcof64 the new version is active in Google Play. Please, let us know whether the issue has been solved.

**Comment by Marcof64** [comment] 2022-04-28 15:30
Now I am able to get recognitions 

Canging model requires to kill and relaunch app but works

Are you getting good framerates in the xiomi?

**Comment by sergiossm** [comment] 2022-04-28 17:00
> Now I am able to get recognitions

Glad we got it fixed @Marcof64 👍

> Canging model requires to kill and relaunch app but works
 
We're not getting any crash reports about this, can you uninstall the app (removing its data and cache from the Android settings) and reinstall it again? Please, come back to us if the issue persists.

> Are you getting good framerates in the xiomi?

Framerates are quite good in relatively new Android devices (from 2021 onward). Here's a video of the app running on a Xiaomi Mi 11 and changing models.

https://user-images.githubusercontent.com/26566365/165805393-5e632cb1-7bbb-4b7e-8489-cfcef6341a1e.mp4

**Comment by Marcof64** [comment] 2022-04-28 17:17
Da: Sergio Sánchez ***@***.***> 
Inviato: giovedì 28 aprile 2022 19:01
A: ultralytics/hub ***@***.***>
Cc: Marcof64 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [ultralytics/hub] Pixel 3i (Issue #23)

 

Now I am able to get recognitions

Glad we got it fixed @Marcof64 <https://github.com/Marcof64>  👍

Canging model requires to kill and relaunch app but works

We're not getting any crash reports about this, can you uninstall the app (removing its data and cache from the Android settings) and reinstall it again? Please, come back to us if the issue persists.

>>Changing model has no effect as the frame rate does not change and I get a “loading YOLOv5 xxx” superimposed on the images. Only when I kill the app and restart it do the change take effect and the message superimposed is no longer present

Framerates are quite good in relatively new Android devices (from 2021 onward). Here's a video of the app running on a Xiaomi Mi 11 and changing models.

https://user-images.githubusercontent.com/26566365/165805393-5e632cb1-7bbb-4b7e-8489-cfcef6341a1e.mp4

**Comment by sergiossm** [comment] 2022-04-28 17:40
> Changing model has no effect as the frame rate does not change and I get a “loading YOLOv5 xxx” superimposed on the images. Only when I kill the app and restart it do the change take effect and the message superimposed is no longer present

How long are you holding before killing the app? Recreating the detector might take a while. Your device operates on a Snapdragon 670 -if I'm not mistaken- versus a Snapdragon 888 on our side, that's probably the reason why the app seems to get stuck changing the model.

Please, follow these steps:
1. Remove app data and cache from the Android settings.
2. Uninstall the app
3. Reinstall from Google Play
4. Change from YOLOv5**n** (selected by default) to YOLOv5**s**. Wait for 1 minute or until the loading indicator disappears.

Please, let us know if the issue persists after following the previous steps.

**Comment by Marcof64** [comment] 2022-04-28 17:43
You are right, it’s just the phone that is very slow.

 

All is fine.

 

Thanks

 

Marco

 

Da: Sergio Sánchez ***@***.***> 
Inviato: giovedì 28 aprile 2022 19:40
A: ultralytics/hub ***@***.***>
Cc: Marcof64 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [ultralytics/hub] Pixel 3i (Issue #23)

 

Changing model has no effect as the frame rate does not change and I get a “loading YOLOv5 xxx” superimposed on the images. Only when I kill the app and restart it do the change take effect and the message superimposed is no longer present

How long are you holding before killing the app? Recreating the detector might take a while. Your device operates on a Snapdragon 670 -if I'm not mistaken- versus a Snapdragon 888 on our side, that's probably the reason why the app seems to get stuck changing the model.

Please, follow these steps:

1.	Remove app data and cache from the Android settings.
2.	Uninstall the app
3.	Reinstall from Google Play
4.	Change from YOLOv5n (selected by default) to YOLOv5s. Wait for 1 minute or until the loading indicator disappears.

Please, let us know if the issue persists after following the previous steps.

**Comment by sergiossm** [comment] 2022-04-28 18:16
Thank you for your feedback @Marcof64. Closing the issue.

**Closed** 2022-04-30 03:22 UTC
Labels: bug

**Comment by Marcof64** [comment] 2022-05-09 09:11
Hello Sergio,

 

COMM3000 has bought non-commercial access to iOS and Android source code for the app, as far as you know has the Android source code been published in the reserved area?

 

If so can you help us locate it?



We have ordered a phone identical to the one you indicated to test it.

 

Thanks

 

Marco

 

Da: Sergio Sánchez ***@***.***> 
Inviato: giovedì 28 aprile 2022 20:17
A: ultralytics/hub ***@***.***>
Cc: Marcof64 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [ultralytics/hub] Pixel 3i (Issue #23)

 

Thank you for your feedback @Marcof64 <https://github.com/Marcof64> . Closing the issue.

**Comment by stefani-kovachevska** [comment] 2022-05-09 09:34
Hi @Marcof64, 

> COMM3000 has bought non-commercial access to iOS and Android source code for the app, as far as you know has the Android source code been published in the reserved area? If so can you help us locate it?

COMM3000 should have access to 4 repositories, including _YOLOv5 Flutter_ which supports YOLOv5 on both Android and iOS. You should be able to access them from [Emiliano](https://github.com/emilianotre)'s account. 

> We have ordered a phone identical to the one you indicated to test it.
Great to hear, we're excited to hear your feedback! 😃 

If there's anything else we can help with, please let us know.

Stefani Kovachevska 
Project Manager @Ultralytics

**Comment by Marcof64** [comment] 2022-05-09 09:39
Thanks!

 

Da: Stefani ***@***.***> 
Inviato: lunedì 9 maggio 2022 11:35
A: ultralytics/hub ***@***.***>
Cc: Marcof64 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [ultralytics/hub] Pixel 3i (Issue #23)

 

Hi @Marcof64 <https://github.com/Marcof64> ,

COMM3000 has bought non-commercial access to iOS and Android source code for the app, as far as you know has the Android source code been published in the reserved area? If so can you help us locate it?

COMM3000 should have access to 4 repositories, including YOLOv5 Flutter which supports YOLOv5 on both Android and iOS. You should be able to access them from Emiliano <https://github.com/emilianotre> 's account.

We have ordered a phone identical to the one you indicated to test it.
Great to hear, we're excited to hear your feedback! 😃

If there's anything else we can help with, please let us know.

Stefani Kovachevska
Project Manager @ultralytics <https://github.com/ultralytics>

**Comment by kingmacth** [comment] 2022-06-14 07:15
> Android source code
Hello Marcof64
Where can I find the Android source code? Did you finally get it?

**Comment by Marcof64** [comment] 2022-10-11 07:47
Hello Stefani,

 

Yes we have access to flutter code but we don’t have access to the code for the newly released Android app now available in the play store!

 

Thanks

 

Marco

 

Da: Stefani ***@***.***> 
Inviato: lunedì 9 maggio 2022 11:35
A: ultralytics/hub ***@***.***>
Cc: Marcof64 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [ultralytics/hub] Pixel 3i (Issue #23)

 

Hi @Marcof64 <https://github.com/Marcof64> ,

COMM3000 has bought non-commercial access to iOS and Android source code for the app, as far as you know has the Android source code been published in the reserved area? If so can you help us locate it?

COMM3000 should have access to 4 repositories, including YOLOv5 Flutter which supports YOLOv5 on both Android and iOS. You should be able to access them from Emiliano <https://github.com/emilianotre> 's account.

We have ordered a phone identical to the one you indicated to test it.
Great to hear, we're excited to hear your feedback! 😃

If there's anything else we can help with, please let us know.

Stefani Kovachevska
Project Manager @ultralytics <https://github.com/ultralytics>

**Comment by Marcof64** [comment] 2022-10-11 09:24
Super!
Thanks

**Comment by UltralyticsAssistant** [comment] 2024-01-08 16:03
You're welcome, @Marcof64! If you have any more questions or need further assistance in the future, don't hesitate to reach out. Happy to help! 😊 Have a great day!
