### ISSUE TITLE
Regarding image dataset rotation

### ISSUE THREAD

**Issue by snowfluke** [ultralytics/hub#853] opened 2024-09-28 11:25 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

Hi, I think I found a bug the way the web (HUB) render an image. In my computer, all the dataset images appear to be in the correct orientation, several images before has been rotated. Then I upload the images, but several images orientation comes back. To get a better understanding of the problem, here's the picture:

![image](https://github.com/user-attachments/assets/a34a9534-6ba1-411d-9aad-e05da1fd7f1a)

### Environment

- Computer: MSI GF63 Thin
- OS: Windows 11
- Browser: Brave v1.70.119

### Minimal Reproducible Example

1. Rotate an image in Windows 11 default picture preview app
2. Save it as the same filename and overwrite it
3. Upload the image as dataset to hub

**Comment by UltralyticsAssistant** [comment] 2024-09-28 11:25
👋 Hello @snowfluke, thank you for reporting an issue with the [Ultralytics HUB](https://github.com/ultralytics/hub) 🚀! 

Please check out our [HUB Docs](https://docs.ultralytics.com/hub) for more insights on various functionalities:

- [**Quickstart**](https://docs.ultralytics.com/hub/quickstart)
- [**Datasets: Preparing and Uploading**](https://docs.ultralytics.com/hub/datasets)
- [**Projects: Creating and Managing**](https://docs.ultralytics.com/hub/projects)
- [**Models: Training and Exporting**](https://docs.ultralytics.com/hub/models)
- [**Integrations**](https://docs.ultralytics.com/hub/integrations)
- [**Ultralytics HUB App**](https://docs.ultralytics.com/hub/app)

As you reported a 🐛 bug, could you please provide additional screenshots and steps to ensure the issue is clear? A [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) will greatly assist us in diagnosing and resolving the problem.

Please note that this is an automated response, and an Ultralytics engineer will also review and assist you soon. Thank you for your understanding and patience! 😊

**Comment by pderrenger** [comment] 2024-11-09 00:56
@snowfluke hello! 😊

Thank you for bringing this to our attention. It seems like the issue might be related to how image metadata, specifically EXIF orientation data, is being handled during the upload process. When images are rotated using certain applications, the rotation might be stored in the metadata rather than being applied directly to the image pixels. This can sometimes lead to discrepancies in how images are displayed across different platforms.

To help resolve this, you can try the following steps:

1. **Strip EXIF Data:** Use an image editor to rotate the image and save it without EXIF data. This ensures that the rotation is applied directly to the image pixels.
   
2. **Re-upload the Image:** After saving the image without EXIF data, try uploading it again to the Ultralytics HUB.

If the issue persists, please ensure that you are using the latest version of the Ultralytics HUB. If the problem continues, feel free to update this thread with any additional details, and we'll be happy to assist further.

Thank you for your patience and for using Ultralytics HUB! 🚀

**Comment by yogendrasinghx** [comment] 2024-11-12 15:23
@snowfluke Thank you for reporting this issue and for your patience. As mentioned by @pderrenger, it appears the issue may be related to EXIF metadata affecting image orientation during upload. Please try rotating the image in an editor and saving it without EXIF data, then re-uploading it to the Ultralytics HUB.

If the issue persists after trying this, let us know, and we’ll investigate further. Thank you for helping us improve the platform!

**Closed** 2024-11-13 01:00 UTC
Labels: bug
