### ISSUE TITLE
Can not get my storage back

### ISSUE THREAD

**Issue by vwyLss** [ultralytics/hub#688] opened 2024-05-17 21:23 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

I have only one dataset with the size of 2.6 GB but in my account I have no storage left. I can not upload new datasets.

Here is an id of one of my models: https://hub.ultralytics.com/models/dn4UiKYhJPoLGXBWIY2q

### Environment

Ultralytics HUB Version
v0.1.42
Client User Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 OPR/109.0.0.0
Operating System
Win32
Browser Window Size
1866 x 994
Server Timestamp
1715977589

### Minimal Reproducible Example

![Ekran Görüntüsü (4)](https://github.com/ultralytics/hub/assets/123624393/b8e17ad4-07f4-4f31-9c06-84d60230b94f)

This is my only dataset that's in the hub.

**Comment by pderrenger** [comment] 2024-05-17 23:19
Hello!

Thanks for reaching out and for providing detailed information about your storage issue on the HUB 🙌. It sounds like there could be a discrepancy in the storage calculation. This could potentially be caused by reserved space from previously deleted data that hasn't been fully cleared yet. 

Could you please try the following steps:
1. Refresh your account details in the settings area.
2. Log out, then log back in to reset the session and update any cached settings.

If the issue persists, please provide a screenshot of your current storage usage displayed in the account settings, if possible, without any sensitive information.

We appreciate your patience and cooperation in resolving this. Thank you for using Ultralytics HUB!

**Comment by vwyLss** [comment] 2024-05-18 18:36
I tried what you said but did not get a solution

Here is the screenshot:

![Ekran Görüntüsü (5)](https://github.com/ultralytics/hub/assets/123624393/b3a86e0f-c9a7-4cd5-a070-8df49b296f63)

**Comment by vwyLss** [comment] 2024-05-18 18:37
I tried what you said but it did not change anything

Here is the screenshot:

![Ekran Görüntüsü (5)](https://github.com/ultralytics/hub/assets/123624393/7704f943-5aeb-43d8-a63c-bdbec158ba98)

**Comment by sergiuwaxmann** [comment] 2024-05-18 18:39
@vwyLss Our development team will investigate your issue. I will keep you updated.

Please accept our apologies for the inconvenience.

**Comment by sergiuwaxmann** [comment] 2024-05-20 10:04
@vwyLss Looks like some of your datasets are soft deleted.

When you delete a dataset, model or project you are actually performing a soft delete.
In order to completely delete a dataset, model or project, you need to go to the [Trash](https://hub.ultralytics.com/trash) page and click on the **Empty Trash** button or delete them one by one. Did you do this?
Read more about [deleting a dataset](https://docs.ultralytics.com/hub/datasets/#delete-dataset), [deleting a project](https://docs.ultralytics.com/hub/projects/#delete-project) and  [deleting a model](https://docs.ultralytics.com/hub/models/#delete-model).

**Comment by glenn-jocher** [comment] 2024-05-20 10:09
@sergiuwaxmann might make sense to display a breakdown here of what's used so users can see the breakdown of models/datasets/trash and then a link to empty the trash?

Something closer to what macOS shows for example would be super helpful I think:

<img width="827" alt="Screenshot 2024-05-20 at 12 09 25" src="https://github.com/ultralytics/hub/assets/26833433/8f9dbd84-ef7d-494f-bc4a-879022d226aa">

**Comment by sergiuwaxmann** [comment] 2024-05-20 10:41
@glenn-jocher That is a great idea! 🚀 I will add it to our TODO list.

**Closed** 2024-06-14 09:29 UTC
Labels: bug
