### ISSUE TITLE
Custom model using timed training doesn't allow its use

### ISSUE THREAD

**Issue by JhonFrederick** [ultralytics/hub#627] opened 2024-04-01 16:46 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Currently with our team are using YOLOV8 models and we decide to train our own model using cloud training with time training to test this option. 

According to the documentation, we thought that at the end of the given time, the model would be trained to that point and allow it to be used, but this does not seem to be the case. I don't have much experience with training models and I was exploring the platform, for this reason, I want to know if there is something I am doing wrong or have misunderstood?
> Timed Training: The timed training feature allows you to fix the time duration of the entire training process and also determines the estimated amount before the start of training.

This is the final status of the model training, we thought that buying more credits would enable the "Resume training" button, but it didn't happen.

![WhatsApp Image 2024-04-01 at 11 04 28 AM](https://github.com/ultralytics/hub/assets/20525802/3dec20e3-c9dc-40e5-ac43-5bdda8d9e318)

I appreciate your help in advance

**Comment by sergiuwaxmann** [comment] 2024-04-01 17:35
Hello @JhonFrederick!

First of all, please accept our apologies for the inconvenience caused.

Based on the screenshot you shared, you used Epochs training (not Timed training) but I would like to investigate this further. Can you please share your model ID (you can find it in the URL) here?

Also, looking at the right side of your screenshot, I can see negative epochs which makes me think that you might face an issue we are currently trying to solve (#622).

**Comment by JhonFrederick** [comment] 2024-04-01 18:25
I remember setting the timed training to a value of 1 day, but now I'm not sure. Mainly because I am currently running other test with Epoch Training and the way the information is displayed was not the same as the attempt shown in the screenshot.  But since you mention the issue, it could be due to that. 
Model ID: FuVEbxOoAcWJCFA7fa9m

**Comment by UltralyticsAssistant** [comment] 2024-04-01 21:27
@JhonFrederick hello again, and thank you for providing the model ID and additional details. It clarifies your situation significantly.

Given the information and your experience with both timed and epoch training, it indeed sounds like the unusual behavior you encountered with the model `FuVEbxOoAcWJCFA7fa9m` might be related to the issue we're currently addressing. 

I appreciate your patience and understanding as we work towards resolving this. In the meantime, it seems you've correctly identified different billing behaviors between timed and epoch training—timed training estimates your total cost upfront based on the duration, whereas epoch training's cost accumulates over time.

Your observations are indeed relevant and help us ensure the platform works as expected for everyone. We'll keep you updated on our progress with the mentioned issue. Please, stay tuned! 😊

**Comment by JhonFrederick** [comment] 2024-04-02 01:17
![image](https://github.com/ultralytics/hub/assets/20525802/1ab97107-7bd1-4219-b118-0fb6a933ac0d)

According to the above screen, my second model finished (with epoch training) with ID: tj2HLEVdErYxgunZzH9Z, but when I go to preview or deployment tab, I get the following message "Model not trained".
![image](https://github.com/ultralytics/hub/assets/20525802/305a038b-8a1a-4454-b8f5-cf950db5a43b)

Attached a screenshot of the billing summary, which shows the different attempts to complete the training.
![image](https://github.com/ultralytics/hub/assets/20525802/aff237db-b32c-44e5-b29e-a5e76e4eab7e)

Please tell me in this case what I could be doing wrong so that it doesn't allow me to use the trained model?

I appreciate your help again in advance

**Comment by UltralyticsAssistant** [comment] 2024-04-02 03:06
@JhonFrederick hello again!

Thanks for reaching out with these details. It looks like an issue on our end where the model's training status hasn't correctly updated in the UI, despite the training completion. This misalignment is likely causing the "Model not trained" message you're seeing.

For now, could you try refreshing the page or logging out and back into the platform to see if that helps sync the status? Sometimes, a simple refresh can resolve such discrepancies.

If the issue persists, rest assured, we're here to help! We'll investigate further using the model ID `tj2HLEVdErYxgunZzH9Z` you provided and ensure your model becomes accessible for preview and deployment.

Again, we truly appreciate your patience and feedback as we work to improve the platform. Stay tuned! 🌟

**Comment by JhonFrederick** [comment] 2024-04-09 21:51
Hi,

I tried again with another test using epoch training, but again I had problems, I attached proof of this.
Model ID: `xrGz5bRPDQvMniPK8eIR`
![image](https://github.com/ultralytics/hub/assets/20525802/82092588-de53-45e6-bfd5-e1f1c0a6b8ad)

Billing information
![image](https://github.com/ultralytics/hub/assets/20525802/fba60cf9-af29-471d-af72-9e22aed8d21f)

In this case the training was going well up to a certain point, after 75%, I had to retry the training a couple of times until it was completed, but without the possibility of using the model, until it finally ended in the state shown

**Comment by pderrenger** [comment] 2024-04-10 04:47
Hello @JhonFrederick,

Thank you for your patience and for sharing the details of your latest attempt! 🌟

We're sorry to hear that you've encountered further issues. Based on your description and the screenshots, it seems like the training process completes, but the model remains unusable due to an issue with the final model weights upload or status update.

We are currently investigating these issues to prevent them from occurring in the future. In the meantime, we have credited your account for the inconvenience caused by this training attempt with model ID `xrGz5bRPDQvMniPK8eIR`.

If you haven't already, we suggest attempting a fresh training session, ensuring that all prior settings and data are correctly configured. If the problem persists, please let us know—we're here to support you.

Thanks again for your understanding and cooperation.

**Comment by pderrenger** [comment] 2024-04-13 22:48
Hey @JhonFrederick,

Oh no, sorry to hear about the troubles with your recent training attempt under the model ID `xrGz5bRPDQvMniPK8eIR`. 😕 It seems like the issue persists even after multiple retries, which is far from ideal.

We appreciate you providing the screenshots and model ID, as this information is crucial for us to diagnose what went wrong. Your case seems to show a pattern that we need to investigate more deeply to ensure it doesn't happen in the future.

For now, let's try the following steps to see if we can resolve or work around the issue:
1. **Refreshing the Page**: Sometimes, the status update might lag in the UI. A simple refresh can help check if the model's actual state wasn't properly reflected.
2. **Check the Logs**: If possible, review the training logs available within the platform for any error messages or warnings near the point where issues began. This could provide clues on why the training didn't complete as expected.
3. **Contact Support**: Since this is a recurring problem, I'll escalate this issue with the model ID you've provided to our technical support team for further investigation. We aim to resolve these kinds of issues promptly.

We're genuinely sorry for any inconvenience caused and are here to assist you through this process. Your understanding and patience as we work to fix this is greatly appreciated. 🛠️

Stay tuned for updates, and thanks again for reaching out!

**Comment by sergiuwaxmann** [comment] 2024-04-15 12:10
Hello @JhonFrederick!

I apologize once again for the inconvenience.

Based on our internal tests, we've observed that, in approximately 10% of cases, the final weights upload fails. This results in the model being stuck at 100%. If the training is resumed, the session fails since the training has already completed. Our team is currently working on updating the logic for uploading weights to the Ultralytics HUB to prevent this issue.

Meanwhile, we have refunded the account balance you used.

CC @hassaanfarooq01

**Comment by sergiuwaxmann** [comment] 2024-04-22 10:56
Hello @JhonFrederick!
Great news! Our team has released a fix for the issue you reported. You should no longer experience this problem in new Cloud Training sessions.
Thanks for your patience!

**Closed** 2024-04-22 10:59 UTC
Labels: question, fixed

**Comment by JhonFrederick** [comment] 2024-04-22 13:48
Hi,

Was it released today? because I was doing tests with epoch Training and they all gave me negative epochs
Model ID: `Jw8BPBb2kmX0i7lErCiP`, `j8NsAEFksZH65pEmt0e1`, `xvvlSW8VL1YTsCGM5jxr`, `yEAC9FrDTMgJBxvk42wp`, 
Each model had finished with 100% but did not allow using the model and after a retry ended with -1 epochs.

After finishing a epoch training that I'm running, I try the Timed training again and I will comment on my results

**Comment by sergiuwaxmann** [comment] 2024-04-22 15:42
Hello @JhonFrederick!
We released the fix today (when I sent you the message above).
Unfortunately, the recent fix does not apply to models trained on earlier versions, so you will need to retrain your models. We sincerely apologize for the inconvenience this causes.

**Comment by JhonFrederick** [comment] 2024-04-23 15:41
> Hi,
> 
> Was it released today? because I was doing tests with epoch Training and they all gave me negative epochs Model ID: `Jw8BPBb2kmX0i7lErCiP`, `j8NsAEFksZH65pEmt0e1`, `xvvlSW8VL1YTsCGM5jxr`, `yEAC9FrDTMgJBxvk42wp`, Each model had finished with 100% but did not allow using the model and after a retry ended with -1 epochs.
> 
> After finishing a epoch training that I'm running, I try the Timed training again and I will comment on my results

Finally my test with epoch training was successful, the test was run with 5 epochs (I didn't want to lose credits like with the other models I mentioned above). But when execute a timing training, again get negative epochs and I cannot make click in `Resumen Training` button.

Model ID: `M16CdXdrDQNg0h7hGWJw`

![image](https://github.com/ultralytics/hub/assets/20525802/b4353684-8bd9-4856-9da4-fc25c4a9cddc)
![image](https://github.com/ultralytics/hub/assets/20525802/058dade9-253c-49c5-a1ea-a9103188bf1b)
![image](https://github.com/ultralytics/hub/assets/20525802/52bc08ef-a804-4b87-9783-4e4475f26e2e)

I paid for the "Hub Pro" plan expecting to take advantage of the cloud training, but for the entire month I basically never took advantage of it. It's a shame because my plan ends today and I was hoping to test with a better trained model but the issue still persists. 

It should be noted that my problem was initially due to timing training, as I did not know the number of epochs my training could take.

I hope that at least all the failed models, including this, allow the team to correct the problem.

**Comment by sergiuwaxmann** [comment] 2024-04-23 17:11
I am sorry you had a negative experience with Cloud Training due to issues on our end and we hope these won't happen again. Our team will look at the failed models and refund the account balance spent on them.
