### ISSUE TITLE
Why can’t I continue training in cloud?

### ISSUE THREAD

**Issue by rolurq** [ultralytics/hub#602] opened 2024-03-07 08:25 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I have a model training and for some reason it disconnected. I see a text to resume training but is not clickable. 
<img width="1180" alt="image" src="https://github.com/ultralytics/hub/assets/13684824/9ecefb07-8acd-4441-9fe0-d7364cadc9a1">

**Comment by UltralyticsAssistant** [comment] 2024-03-07 15:46
@rolurq hello! 👋

It sounds like you're experiencing an issue with resuming training in the cloud. Typically, the option to resume training should be clickable, allowing you to pick up right where you left off. If it's not clickable, this could be due to a temporary glitch or a session timeout.

Here are a few steps you can take to troubleshoot:
1. **Refresh the Page**: Sometimes, a simple refresh can resolve the issue.
2. **Check Your Internet Connection**: Ensure your internet connection is stable.
3. **Clear Browser Cache**: Occasionally, cached data can cause display issues on web pages.
4. **Try a Different Browser**: If the issue persists, trying a different web browser can help identify if the problem is browser-specific.

If none of these steps work, it might be a more specific issue that needs direct attention. Please consider providing detailed feedback through the "Feedback" option on the platform or by creating a detailed issue on our GitHub repository, mentioning any error messages or unusual behavior you've observed.

For more detailed guidance on managing your training sessions, please refer to our documentation at https://docs.ultralytics.com/hub.

We appreciate your patience and are here to help you get back to training your models smoothly! 🚀

**Comment by rolurq** [comment] 2024-03-08 12:02
> @rolurq hello! 👋
> 
> It sounds like you're experiencing an issue with resuming training in the cloud. Typically, the option to resume training should be clickable, allowing you to pick up right where you left off. If it's not clickable, this could be due to a temporary glitch or a session timeout.
> 
> Here are a few steps you can take to troubleshoot:
> 
> 1. **Refresh the Page**: Sometimes, a simple refresh can resolve the issue.
> 2. **Check Your Internet Connection**: Ensure your internet connection is stable.
> 3. **Clear Browser Cache**: Occasionally, cached data can cause display issues on web pages.
> 4. **Try a Different Browser**: If the issue persists, trying a different web browser can help identify if the problem is browser-specific.
> 
> If none of these steps work, it might be a more specific issue that needs direct attention. Please consider providing detailed feedback through the "Feedback" option on the platform or by creating a detailed issue on our GitHub repository, mentioning any error messages or unusual behavior you've observed.
> 
> For more detailed guidance on managing your training sessions, please refer to our documentation at https://docs.ultralytics.com/hub.
> 
> We appreciate your patience and are here to help you get back to training your models smoothly! 🚀

Followed this steps, however the result is the same. I filled a report with the feedback option. It's very frustrating noty having an actual person look into these issues.

**Comment by UltralyticsAssistant** [comment] 2024-03-08 14:15
I'm really sorry to hear that the issue persists, @rolurq. I understand how frustrating it can be when things don't work as expected, especially when you're eager to continue your work. Thank you for taking the time to submit a report through the feedback option. That was the right step to ensure that your issue gets the attention it needs.

Our team reviews every piece of feedback and issue report we receive. While I wish I could resolve this directly for you here, rest assured that by submitting a report, you've alerted our team to the problem, and they'll be looking into it. Our goal is to address issues as quickly as possible, so someone from our team should be reaching out to you or providing an update soon.

In the meantime, if there's anything new you notice about the issue or if there are any changes, updating your report with that information can be very helpful. Your patience and understanding are greatly appreciated as we work to resolve this for you. 🌟

**Comment by kalenmike** [comment] 2024-03-08 15:02
@rolurq I responded on your other issue and a fix has been deployed. Apologies for any inconvenience caused.
https://github.com/ultralytics/hub/issues/604

**Closed by kalenmike** 2024-03-08 15:02 UTC
Labels: question
