### ISSUE TITLE
Model upload 

### ISSUE THREAD

**Issue by Valenso-ua** [ultralytics/hub#26] opened 2022-04-30 09:18 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

can I upload my already trained model to your service?

### Additional

didn't see how to do it

**Comment by glenn-jocher** [comment] 2022-04-30 23:01
@Valenso-ua duplicate of https://github.com/ultralytics/hub/issues/25. 

No, it is not possible to upload trained models to HUB, but you can upload your dataset to HUB and then train a new model there.

**Comment by glenn-jocher** [comment] 2022-04-30 23:02
@Valenso-ua closing issue to move convo to #25

**Closed by glenn-jocher** 2022-04-30 23:02 UTC
Labels: duplicate, question
