### ISSUE TITLE
I am a Hub Pro User, Trying to Upload Data For Pose detection, after upload its showing Unable to process the dataset error.

### ISSUE THREAD

**Issue by kumarneeraj2005** [ultralytics/hub#665] opened 2024-04-28 02:27 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

Hello, Ultralytics Hub Pro Team.
While uploading data for pose detection, I receive an error stating "Unable to process the dataset". Could you please look at this issue? 
Dataset size - 10.9 GB.
I manually checked that all of the label formats and folder structures are correct.
![Screenshot 2024-04-28 at 7 56 28 AM](https://github.com/ultralytics/hub/assets/8565041/ca2ba859-9b76-4737-bfcf-4447d9113edc)
![Screenshot 2024-04-28 at 7 56 28 AM](https://github.com/ultralytics/hub/assets/8565041/9a9e495e-dd9c-43d1-a214-8da99f8bf791)

**Comment by pderrenger** [comment] 2024-04-28 05:23
@kumarneeraj2005 hello! 😊

Thanks for reaching out and for being a part of our Hub Pro community. It seems like you've done a preliminary check on the dataset and everything looks in place, which is great! The "Unable to process the dataset" error can sometimes be caused by transient issues with our servers or by specific peculiarities within the dataset that aren't immediately obvious.

Here's what we recommend:
1. **Retry the upload** - Sometimes, giving it another go can solve the issue if it was related to a temporary server hiccup.
2. **Check for hidden files or corrupt images** - Occasionally, hidden files or corrupt images in the dataset can cause processing to fail. Make sure all files are in the expected format and can be opened without issues.
3. **Validate dataset size and format** - Ensure your dataset size is within the limits for Pro users and that all files adhere to the expected formats for pose detection datasets.

If after trying these steps you're still facing the issue, could you provide us with some more details? Specifically:
- Are there any specific file types in your dataset?
- Have you been able to successfully upload other datasets for pose detection or is this the first one?

We're here to help you get this resolved! Thanks for your patience and for being a valued member of the Ultralytics community. For further assistance, please refer to our docs at https://docs.ultralytics.com/hub which might give you more detailed guidance on dataset requirements and troubleshooting steps.

**Comment by kumarneeraj2005** [comment] 2024-04-28 06:28
we did all these 3 steps and everything is fine but still getting same error. Could you please check from backend ?? if needed i will share details, please provide your support email ID. We are struggling from yesterday. We tried more than 10 times.

**Comment by sergiuwaxmann** [comment] 2024-04-28 06:41
@kumarneeraj2005 
You can validate your dataset like this (before uploading it to Ultralytics HUB):
```python
from ultralytics.hub import check_dataset
check_dataset('path/to/coco8.zip')
```
Please let us know if the local validation is successful. If it isn't, the `check_dataset` function should give you insights to help you figure out what is wrong with your dataset.

**Comment by kumarneeraj2005** [comment] 2024-04-29 10:27
Hello, Ultralytics team, could you please let me know, if you have any support option for Pro subscription ? or its simply Pro? very frustrated with your solution.

**Comment by kumarneeraj2005** [comment] 2024-04-29 12:02
@yogendrasinghx @sergiuwaxmann 

![check_size](https://github.com/ultralytics/hub/assets/8565041/10a606cd-fcd3-4a30-ad1a-b7e7b0708d1d)
![check](https://github.com/ultralytics/hub/assets/8565041/1f79a8db-5383-4fac-86eb-850a20115f4d)
![data_upload](https://github.com/ultralytics/hub/assets/8565041/cf1b2c08-1748-4505-9797-9cf3c03915c1)

As you suggested above, everything seems to be fine from our end. Dataset is totally valid as per your platform requirement.

For your reference i am sharing my userID and Project id :

UserID : Healiumdigital@gmail.com 

Please do let me know if anything else is needed.

**Comment by sergiuwaxmann** [comment] 2024-04-29 13:22
@kumarneeraj2005

@Laughing-q discovered the issue occurs when there is an empty array of keypoints in the dataset and created a [PR](https://github.com/ultralytics/ultralytics/pull/10415) to fix this. Thank you for bringing this to our attention.
I will update you as soon as we merge and deploy the fix. Please accept our apologies for the inconvenience caused.

Alternatively, you can remove the 3 background images from your dataset if you do not want to wait for the fix to be merged and deployed.

**Comment by kumarneeraj2005** [comment] 2024-04-29 15:28
@sergiuwaxmann  could you please let me know which 3 background images you are talking about, if possible  give me images detail...

**Comment by sergiuwaxmann** [comment] 2024-04-29 15:40
@kumarneeraj2005 Unfortunately, I do not have access to your dataset but I can see in the [screenshot you shared](https://private-user-images.githubusercontent.com/8565041/326427865-1f79a8db-5383-4fac-86eb-850a20115f4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MDU0MTAsIm5iZiI6MTcxNDQwNTExMCwicGF0aCI6Ii84NTY1MDQxLzMyNjQyNzg2NS0xZjc5YThkYi01MzgzLTRmYWMtODZlYi04NTBhMjAxMTVmNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMTUzODMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjMxMTE3YmRiMGY0ZWE1ZWRmMWY2MjhmODFkMzI1NGI1MDllOTY5M2E3ODgwMWIwNjZkYjk1ZmM1OGFlMGE5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-6pqBqd54yWB_tBWYHMwYidqtv9xmfcB_nNUHqf0LGI) that you have 3 backgrounds.

**Comment by kumarneeraj2005** [comment] 2024-04-30 06:34
@sergiuwaxmann  we will wait for your fix

**Comment by kumarneeraj2005** [comment] 2024-05-01 14:02
@sergiuwaxmann @yogendrasinghx 
![WhatsApp Image 2024-05-01 at 19 26 47](https://github.com/ultralytics/hub/assets/8565041/49f8623c-0e97-47b7-a9fa-d41a54ecaf9b)
![WhatsApp Image 2024-05-01 at 19 27 09](https://github.com/ultralytics/hub/assets/8565041/fa6c45ca-7ea2-444e-a198-932682078b63)

Guys - seems your platform is not ready for Production, its really serious issue. check attached images. When dataset is small its accepting with so called background images and uploading to your platform, but when its large dataset your platform is not able to handle. I request you to please look in this issue on priority basis. O/w cancel my Pro-membership, and i am really serious.

**Comment by glenn-jocher** [comment] 2024-05-02 20:21
Hey @kumarneeraj2005, great news! 🎉 The HUB has been fully updated with all the latest fixes from https://github.com/ultralytics/ultralytics/pull/10415, thanks to the examples you provided for debugging. 🛠️

Please give your dataset upload and training another go, and don't hesitate to reach out if you encounter any more issues or have suggestions for improvement. Your input is incredibly valuable in enhancing our product. Looking forward to hearing from you! 😊

**Comment by kumarneeraj2005** [comment] 2024-05-03 08:16
Thanks, Able to upload dataset.
While training on your cloud it showing 116 hours for 64K images, could you please tell me is it normal behaviour ?? 
Is any way to reduce the training time ?  and can we have an option to select better GPU except your T4.
![image](https://github.com/ultralytics/hub/assets/8565041/e314dada-3268-4946-a21f-8901c92c5b3e)

**Comment by sergiuwaxmann** [comment] 2024-05-03 10:20
@kumarneeraj2005 I am glad the upload works. Once again, thank you for bringing this to our attention!
The estimated remaining training time is adjusted during training (it takes us a few epochs to calculate remaining time more accurately).

**Comment by kumarneeraj2005** [comment] 2024-05-05 09:13
@sergiuwaxmann @glenn-jocher   could you please explain why your system is deducting 2 bills for single model training ??
<img width="1291" alt="image" src="https://github.com/ultralytics/hub/assets/8565041/62408651-0a23-4e02-a977-22cbd037aa40">

**Comment by sergiuwaxmann** [comment] 2024-05-05 12:35
@kumarneeraj2005 It looks like you resumed training.
This might be a UI issue (not showing the first training session as completed). I will investigate our system and refund the extra charges if the balance was subtracted two times.

**Comment by glenn-jocher** [comment] 2024-05-05 15:10
> @glenn-jocher Thanks, Able to upload dataset. While training on your cloud it showing 116 hours for 64K images, could you please tell me is it normal behaviour ?? Is any way to reduce the training time ? and can we have an option to select better GPU except your T4. ![image](https://private-user-images.githubusercontent.com/8565041/327692087-e314dada-3268-4946-a21f-8901c92c5b3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MjIwMTgsIm5iZiI6MTcxNDkyMTcxOCwicGF0aCI6Ii84NTY1MDQxLzMyNzY5MjA4Ny1lMzE0ZGFkYS0zMjY4LTQ5NDYtYTIxZi04OTAxYzkyYzViM2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDVUMTUwODM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2Q0ZDVmYzExOGU0ZmYyZGMxZjM1ZmM3MDU1YzFjNjI1NjE1ZjM2YmM4ODg1YTNkM2VjZDI3NTI1NDAxMjc3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1BzUx993SPygjHJjpx5QYEfuYiOUYzG8uB0c-jlsDYM)

@kumarneeraj2005 hi there! About your training time question, yes this is a long time! We are working on supporting newer GPUs soon like NVIDIA L4 GPUs and NVIDIA L40S GPUs from the Ada-Lovelace generation which should be able to complete your training much faster. Hopefully we will have these updates in place over the next few months as we continue to update HUB with the best features and fixes.

**Comment by kumarneeraj2005** [comment] 2024-05-07 07:13
> @kumarneeraj2005 It looks like you resumed training. This might be a UI issue (not showing the first training session as completed). I will investigate our system and refund the extra charges if the balance was subtracted two times.

@sergiuwaxmann  any update on this ?

**Comment by sergiuwaxmann** [comment] 2024-05-07 07:15
@kumarneeraj2005 I replied on the [other issue](https://github.com/ultralytics/hub/issues/675#issuecomment-2095956760) you opened.

**Closed** 2024-05-07 08:04 UTC
Labels: bug, fixed
