### ISSUE TITLE
App and desktop not syncing

### ISSUE THREAD

**Issue by robathanjames** [ultralytics/hub#482] opened 2023-11-25 22:54 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

I made a report before but I can’t access it anymore, even though the problem was never fixed.

my desktop and app don’t sync. I pay for the service and on the app it says I have the free plan, but on the desktop it shows correctly.

none of my projects, datasets or models show up on the app. I’ve tried everything- deleting, re-installing, clearing cache/data… nothing.

Please help.
![IMG_1103](https://github.com/ultralytics/hub/assets/97772344/39100c94-3ee6-4798-a83f-b106e5f30645)

### Environment

-Mac m2, tried safari, chrome and edge all work correctly but won’t sync to the app on iOS. I’ve tried on iOS 16 and 17.

### Minimal Reproducible Example

Login to the hub on desktop.
Save a project, upload a dataset or train a model.
Install the hub app on the AppStore
Login
See that you can’t access any of your data.

### Additional

This is super frustrating. It’s been weeks at this point with no fix.

**Comment by UltralyticsAssistant** [comment] 2023-11-26 05:55
@robathanjames hello! I'm sorry to hear about the issues you're experiencing with syncing between our app and desktop environments. Since you've already tried clearing the app's cache and reinstalling it without success, it seems like the problem might be more complex.

Here are a few steps you can take to potentially resolve the issue:

1. **Check Account Details**: Ensure that you are logged in with the same account on both the desktop and mobile app. Sometimes, different account details might lead to a lack of synchronization.

2. **Verify Subscription Status**: On the desktop version, double-check your subscription status to confirm it's active and properly reflecting on your account.

3. **Review Permissions**: Make sure that you have given the app the necessary permissions to access your data, which might be required for syncing.

4. **Network Configuration**: Ensure that both devices are on a stable internet connection that doesn't have any restrictions blocking the synchronization process.

5. **App Updates**: Verify if there are any updates available for the app that might contain fixes for the syncing issues.

6. **Contact Support**: Since you are a paying customer, you might want to reach out directly to support via the email address provided after your subscription purchase. They could provide a more personalized assistance.

If after following these steps the problem persists, we would appreciate a bug report, following the steps detailed in our documentation for bug submission. While you mentioned you had already raised an issue, if you're unable to access it, submitting a new and detailed report could help our team track and address the syncing problem more effectively.

I understand this situation can be frustrating, and we are committed to resolving it for you. Thank you for your patience and for being a part of the Ultralytics HUB community! 🌟

**Comment by UltralyticsAssistant** [comment] 2023-11-26 22:59
@robathanjames, I apologize for the continued inconvenience and any frustration caused by the automated response system. It's disheartening to hear that you've moved to another platform, but your feedback is crucial for us in identifying and improving areas where our services may not meet user expectations.

While the situation seems to have escalated beyond the usual troubleshooting steps, I want to assure you that our team values your experience and takes issues like this seriously. Customer satisfaction is a top priority, and we strive to provide reliable service.

If you are willing to give us another chance to earn your trust back, please reach out directly to our dedicated support team, which would allow for a more in-depth look at the specific issues pertaining to your account. Our developers are actively working to enhance the platform, and we seek to rectify such sync discrepancies promptly.

Once again, I apologize on behalf of the whole team for the inconvenience you've experienced, and we're thankful for your participation in the Ultralytics HUB community, which helps us to improve continuously. If you decide to give our platform another try, we'll do our best to ensure that your experience is smooth and beneficial. Thank you for your honest feedback. 🙏

**Comment by kalenmike** [comment] 2023-11-29 12:02
@robathanjames Your original issue still exists here:

https://github.com/ultralytics/hub/issues/468

We still need further information as we are not able to reproduce the bug at this point. If you could please re-upload your screenshot showing that your account has empty private and unlisted projects on the original issue.

**Closed by kalenmike** 2023-11-29 12:02 UTC
Labels: bug
