### ISSUE TITLE
Models not loading in IOS App when signed in

### ISSUE THREAD

**Issue by ChrisTheCodingMaster** [ultralytics/hub#817] opened 2024-08-31 23:50 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

I was told by another member of the team to create a new issue to report to development team.

iOS models don’t load on the app when I’m signed in, both private and yolo models once I sign out the yolo models works but can’t access private models. This seems to be an app issue as datasets page seems to be broken.
![IMG_1397](https://github.com/user-attachments/assets/f4f75c87-6c03-479c-b10f-b2d2f5183119)
![IMG_1399](https://github.com/user-attachments/assets/9e11e09d-3209-4c64-b4be-6d9422da731b)

### Environment

App Version: Version 0.9.23 (923)
iOS Versions: iOS beta 18 and iOS 17.5

### Minimal Reproducible Example

1. Logged in to Ultralytics hub on iOS app
2. No models load only the names are present.

**Comment by glenn-jocher** [comment] 2024-09-01 06:26
Hi @ChrisTheCodingMaster,

Thank you for reporting this issue and providing detailed information. It sounds like you're experiencing a problem with loading models in the Ultralytics iOS App when signed in.

To help us investigate further, could you please try the following steps:

1. **Update the App**: Ensure that you are using the latest version of the Ultralytics iOS App. Sometimes, issues are resolved in newer versions.
2. **Clear Cache**: Try clearing the app cache or reinstalling the app to see if that resolves the issue.
3. **Check Network Connection**: Ensure that your device has a stable internet connection, as this can sometimes affect the loading of models.

If the issue persists after trying these steps, please let us know. Additionally, could you confirm if this issue is reproducible on other iOS devices or with different accounts? This information will help us narrow down the potential cause.

We appreciate your patience and cooperation. If you have any further details or screenshots that could assist us, please feel free to share them here.

**Comment by ChrisTheCodingMaster** [comment] 2024-09-01 06:32
hi Mr. Glenn-Jocher, i have already reported about all these bugs in another issue and was asked by you to issue another report but for the development team? I did as you told but I'm confused on whats happening.As I have talked about all this in another Issue.

**Comment by glenn-jocher** [comment] 2024-09-01 10:55
Hi @ChrisTheCodingMaster,

Thank you for following up and providing additional details. We appreciate your diligence in reporting these issues.

To ensure that our development team can effectively investigate and address the problem, could you please confirm if you have tried the following steps:

1. **Update the App**: Make sure you are using the latest version of the Ultralytics iOS App.
2. **Clear Cache**: Try clearing the app cache or reinstalling the app.
3. **Check Network Connection**: Ensure your device has a stable internet connection.

If the issue persists, it would be helpful to know if this problem occurs on other iOS devices or with different accounts. This information can help us identify whether the issue is account-specific or device-specific.

We understand that this might be frustrating, and we are here to help. Your detailed reports are invaluable to us, and we are committed to resolving this issue as quickly as possible.

Thank you for your patience and cooperation. If you have any further details or screenshots that could assist us, please feel free to share them here.

**Comment by ChrisTheCodingMaster** [comment] 2024-09-03 10:20
yes , I have followed all these steps multiple times on different devices including an ipad and two iphones with latest version of the app and ios both ios 17 and 18.

**Comment by glenn-jocher** [comment] 2024-09-03 12:26
Hi @ChrisTheCodingMaster,

Thank you for confirming that you've tried the suggested steps on multiple devices and iOS versions. Given that the issue persists across different devices and the latest app version, it seems like there might be a deeper issue at play.

We appreciate your patience and detailed feedback. To help our development team investigate further, could you please provide the following additional information:

1. **Account Details**: Are you experiencing this issue with a specific account, or does it occur with multiple accounts?
2. **Error Messages**: Are there any error messages or logs that appear when the models fail to load? If so, please share those details.
3. **Steps to Reproduce**: A step-by-step description of how to reproduce the issue, including any specific actions taken before the problem occurs.

Your input is invaluable in helping us diagnose and resolve this issue. We are committed to ensuring that you have a smooth experience with the Ultralytics iOS App.

Thank you for your cooperation and understanding. If you have any further details or screenshots that could assist us, please feel free to share them here. 😊

**Comment by ChrisTheCodingMaster** [comment] 2024-09-04 05:59
1. Same problem with two accounts
2. No error pages but datasets pages doesn’t load indicating a faulty app update perhaps
3. Steps - Install iOS app , sign in models both yolo and private don’t load.
![IMG_1399](https://github.com/user-attachments/assets/7401888c-e0f0-4517-bb71-a5c333d69829)
![IMG_1397](https://github.com/user-attachments/assets/25b156ca-bbfe-4989-89d1-f6a9344011e5)

**Comment by glenn-jocher** [comment] 2024-09-04 13:07
Hi @ChrisTheCodingMaster,

Thank you for providing additional details and screenshots. It’s very helpful for our investigation.

Given that the issue is reproducible with multiple accounts and across different devices, it does seem likely that there might be a problem with the app itself. Here are the next steps we recommend:

1. **Verify Latest Version**: Please ensure you are using the latest version of the Ultralytics iOS App. Sometimes, updates are released to address such issues.
2. **Report to Development Team**: We will escalate this issue to our development team for further investigation. Your detailed steps and screenshots will be invaluable in diagnosing the problem.

In the meantime, you can access your models and datasets via the [Ultralytics HUB web interface](https://hub.ultralytics.com) as a temporary workaround.

We appreciate your patience and cooperation as we work to resolve this issue. If you have any further details or encounter any new issues, please feel free to share them here.

Thank you for your understanding and support! 😊

**Comment by ChrisTheCodingMaster** [comment] 2024-09-05 08:06
1. Yes I am on the latest version 
2. Thank you

**Comment by glenn-jocher** [comment] 2024-09-05 13:29
Hi there,

Thank you for confirming that you're on the latest version. We appreciate your patience as we work to resolve this issue.

Our development team is actively investigating the problem, and your detailed feedback is invaluable. In the meantime, if you have any other questions or need further assistance, feel free to reach out here.

We’re committed to ensuring a smooth experience for you. Thank you for your understanding and support! 😊

If you encounter any new issues or have additional insights, please don't hesitate to share them.

**Comment by sergiuwaxmann** [comment] 2024-09-06 08:04
@ChrisTheCodingMaster It looks like our mobile application is facing issues on some devices/accounts. Our mobile development team will investigate this further and hopefully release an update soon.

**Comment by ChrisTheCodingMaster** [comment] 2024-10-08 01:21
Hi, I just logged back into the app after 3 weeks and it seems public models and private models don't appear either logged in or logged out.

**Comment by pderrenger** [comment] 2024-10-08 02:47
@ChrisTheCodingMaster hello!

Thank you for reaching out and letting us know about the issue. It seems like there might be a persistent problem with the app.

Could you please verify that you are using the latest version of the Ultralytics iOS App? Sometimes updates are released to address such issues. If you're already on the latest version and the problem persists, our development team is actively investigating this.

In the meantime, you can access your models via the [Ultralytics HUB web interface](https://hub.ultralytics.com) as a temporary workaround.

We appreciate your patience and understanding. If you have any other questions or need further assistance, feel free to let us know. 😊

Thank you for your support!

**Comment by sergiuwaxmann** [comment] 2024-10-08 08:35
@ChrisTheCodingMaster This is a known bug that are team will fix in the next release. Apologies for the inconvenience.

**Comment by yogendrasinghx** [comment] 2024-10-30 13:10
@ChrisTheCodingMaster Thank you for your patience and for continuing to work with us to resolve this issue. I’m pleased to inform you that our latest app update, version `0.9.26`, addresses the bug with both public and private models not appearing in the iOS app.

Please update to version `0.9.26`. If the issue persists, try signing out, then uninstalling and reinstalling the app to ensure the changes take effect. We value your detailed feedback, which has been essential in helping us make these improvements. Thank you for your continued support, and please let us know if you encounter any further issues.

**Closed by yogendrasinghx** 2024-10-30 13:10 UTC
Labels: bug
