### ISSUE TITLE
Ultralytics Cloud Training run won't start

### ISSUE THREAD

**Issue by KiwiBryn** [ultralytics/hub#835] opened 2024-09-14 00:42 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

Hi

Late last week I started a training run using a RoboFlow dataset (https://universe.roboflow.com/holstein/rearudderkeypoint) and something went "wrong" as it started and now can't start a new training run or stop the original one. 

The training run starts then disconnects after a while (maybe minutes), then if I try to can start another "Ultralytics Cloud Temporary Unavailable" - "At the moment you can only train one model at a time ....."

Sorry about quality of the Snip screen shots.

Thanks
Bryn

![image](https://github.com/user-attachments/assets/f11dfee2-c0e6-4045-a17f-63b500e6719b)

![image](https://github.com/user-attachments/assets/c47bd7ca-c1b7-4dc2-99b6-682008263378)

![image](https://github.com/user-attachments/assets/9b2ddcda-dda4-44f5-8232-73cd64e23889)

![image](https://github.com/user-attachments/assets/ab6b1ef8-96bd-4cb0-aeee-372420739f7e)

![image](https://github.com/user-attachments/assets/9cbd78ff-9e6b-4d15-b0a8-a67738eabd3a)

![image](https://github.com/user-attachments/assets/78bb8c0d-85aa-417d-8ccf-1f1e6bfa2610)

### Environment

Ultralytics HUB Version v0.1.51
Client User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0
Operating System Win32
Browser Window Size 1262 x 823
Server Timestamp 1726273112

### Minimal Reproducible Example

1. I login to hub
2. Navigate to dataset
3. Start training
4. Wait
5. Disconnection
6. Try start a new training run "Ultralytics Cloud... At the moment you can only train one model at a time..."
7. Logout
8. Login hours later
9. Try steps above
10. Same outcome.

### Additional

Model URL https://hub.ultralytics.com/models/ob8y3fvp44d36onqDKDs

**Comment by UltralyticsAssistant** [comment] 2024-09-14 00:42
👋 Hello @KiwiBryn, thanks for bringing this to our attention! This is an automated response, and an Ultralytics engineer will assist you soon. Let's try to address your issue with some steps and guidelines to help troubleshoot your training run on Ultralytics HUB 🚀.

### Troubleshooting Steps:

1. **Check Training Logs**: 
   - Visit your [Ultralytics HUB Profile](https://hub.ultralytics.com) and look at the logs for the failed training session to identify any specific error messages or indications of what might have gone wrong.

2. **Restart the HUB Session**:
   - Log out of the HUB, clear your browser cache, and log back in. This can often resolve session-related issues.

3. **Network Stability**:
   - Ensure your network connection is stable. Disruptions might cause the training to disconnect.

4. **Verify Dataset Compatibility**:
   - Double-check that your RoboFlow dataset is correctly formatted and exported. Refer to our [Datasets: Preparing and Uploading Guide](https://docs.ultralytics.com/hub/datasets) for details.

5. **Training Resource Availability**:
   - Wait a while before starting a new training session, especially if you're seeing messages about resource availability.

### Reporting a Bug or Issue:
- Please provide clear screenshots and, if possible, record the steps to replicate the issue. This helps in diagnosing and resolving problems quicker.
- You can learn more about creating a good bug report by checking our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example/).

### Next Steps:
- We'll look into your reported issue promptly. In the meantime, please try the steps above.
- Feel free to update this issue with any new insights or follow-up questions.

We appreciate your patience and cooperation!

**Comment by KiwiBryn** [comment] 2024-09-14 01:02
Using Roboflow integration, but when I try export then upload get this error 

![image](https://github.com/user-attachments/assets/612a6c3c-b88a-4a51-a5b9-ea399da4495b)

Even with this error training with other datasets won't start

**Comment by glenn-jocher** [comment] 2024-09-14 09:35
Hello @KiwiBryn,

Thanks for reaching out! It seems like you're encountering an issue with the dataset export and upload process. Let's address this:

### Troubleshooting Steps:

1. **YAML File Adjustment**:
   - As you've discovered, manually editing the YAML file to remove the `test` entry when there are no test images is a good approach. Ensure that the paths and configurations align with your dataset structure.

2. **Roboflow Integration**:
   - Double-check the export settings in Roboflow to ensure compatibility with Ultralytics HUB. Sometimes, re-exporting the dataset with the correct settings can resolve these issues.

3. **Training with Other Datasets**:
   - If training with other datasets is also affected, try clearing your browser cache and restarting your session on Ultralytics HUB. This can sometimes resolve session-related issues.

4. **Verify Latest Versions**:
   - Ensure you are using the latest version of Ultralytics HUB and any related packages. Updates often include bug fixes and improvements.

### Additional Suggestions:

- **Dataset Configuration**: Make sure your dataset configuration aligns with the expected format. You can refer to our [dataset preparation guide](https://docs.ultralytics.com/hub/datasets) for more details.
  
- **Error Logs**: If the issue persists, check the error logs for any additional information that might help diagnose the problem.

Feel free to reach out if you have further questions or need additional assistance. We're here to help! 😊

**Comment by sergiuwaxmann** [comment] 2024-09-15 11:15
@KiwiBryn

Did you import the Roboflow dataset following the instructions from our documentation on Integrations (https://docs.ultralytics.com/hub/integrations)?
If you exported the dataset from Roboflow as a .zip file and uploaded it to Ultralytics HUB, we’ve encountered issues with the format in the past. If this was your approach, please ensure the dataset is in the correct format as outlined in our documentation (https://docs.ultralytics.com/hub/datasets#upload-dataset).

Your issue reminds me of this issue: https://github.com/ultralytics/hub/issues/769. Maybe you have a similar problem (in the dataset)?

**Comment by KiwiBryn** [comment] 2024-09-20 09:03
Hi

After some experimentation, I think my issue was an unfortunate combination of 3 things.

Roboflow Universe dataset yaml file need editing
Maybe a "poisonous cookie" issue
The error message when a training run failed to start. Then, I couldn't start another one(even with different dataset), and the way the training run started then stopped minute(s) later,

There was also something odd with the Roboflow integration, I was getting a Roboflow SQL error when I clicked on my "linked workspace" in Ultralytics integrations. I have been unable to repro this will try a few more approaches.

YoloV8 tooling works well for my application, thank you for following up so quickly.  

@KiwiBryn

**Comment by sergiuwaxmann** [comment] 2024-09-20 09:24
@KiwiBryn Hi!
Unfortunately, we've encountered issues with the Roboflow format in the past, and there's nothing we can do since the problem is not on our end.
Thank you for the feedback! We're glad YOLOv8 is helping you!

**Closed by sergiuwaxmann** 2024-09-20 09:24 UTC
Labels: bug, info needed
