### ISSUE TITLE
Model fails to be exported in Tflite int8 or edge TPU types

### ISSUE THREAD

**Issue by tlong123** [ultralytics/hub#701] opened 2024-05-26 15:18 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

Model ID: 0nS4Xu3l3DPfv1gPyLs2

I have successfully trained a model which I am able to export into Pytorch and ONNX formats, however when I either try to export as an int8 quantized TFlite model or a TensorFlow edge TPU model I get "Failed, retry?" repeatedly with no other information. Is my model unable to be converted into these formats for some reason or is this a bug?

**Comment by sergiuwaxmann** [comment] 2024-05-26 16:09
@tlong123 https://github.com/ultralytics/ultralytics/issues/13019

**Comment by glenn-jocher** [comment] 2024-05-26 17:26
@tlong123 @sergiuwaxmann yes we are working on this in https://github.com/ultralytics/ultralytics/pull/13083, should be resolved this week. Thank you for your patience.

**Comment by sergiuwaxmann** [comment] 2024-05-30 14:44
@tlong123 The problem is now fixed on both `ultralytics` and Ultralytics HUB.

**Closed** 2024-05-30 14:44 UTC
Labels: bug, fixed
