### ISSUE TITLE
Cannot Fetch Dataset with 8.0.76 on colab

### ISSUE THREAD

**Issue by kalenmike** [ultralytics/hub#221] opened 2023-04-18 12:08 UTC
I'm also having this issue now with 8.0.76 on colab

FileNotFoundError                         Traceback (most recent call last)

[/usr/local/lib/python3.9/dist-packages/ultralytics/yolo/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides, _callbacks)
    121             elif self.args.data.endswith('.yaml') or self.args.task in ('detect', 'segment'):
--> 122                 self.data = check_det_dataset(self.args.data)
    123                 if 'yaml_file' in self.data:

4 frames

FileNotFoundError: '/content/datasets/New-Cards-3/New-Cards-3/data.yaml' does not exist

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)

[/usr/local/lib/python3.9/dist-packages/ultralytics/yolo/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides, _callbacks)
    124                     self.args.data = self.data['yaml_file']  # for validating 'yolo train data=url.zip' usage
    125         except Exception as e:
--> 126             raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
    127 
    128         self.trainset, self.testset = self.get_dataset(self.data)

RuntimeError: Dataset '/content/datasets/New-Cards-3/New-Cards-3/data.yaml' error ❌ '/content/datasets/New-Cards-3/New-Cards-3/data.yaml' does not exist

_Originally posted by @Floul1 in https://github.com/ultralytics/hub/issues/207#issuecomment-1507658951_

**Comment by kalenmike** [comment] 2023-04-20 09:39
@floul1 Are you still having this issue?

**Comment by glenn-jocher** [comment] 2023-04-22 20:07
@Floul1 we're not able to reproduce this problem so we've attached a non-reproducible tag to this bug report. If you are still having problems please let us know.

**Comment by Floul1** [comment] 2023-04-22 20:24
Apologies for not responding but this issue does appear to be fixed in latest (tested with 8.0.84)

**Closed** 2023-04-24 15:43 UTC
Labels: bug, non-reproducible

**Comment by UltralyticsAssistant** [comment] 2023-11-14 17:13
@Floul1 thank you for the update. We're glad to hear that the issue is resolved in the latest version. Should you encounter any other problems or have further questions, please don't hesitate to reach out. Happy coding with Ultralytics HUB!
