### ISSUE TITLE
Dataset Upload Failed with Multiple YAML's found

### ISSUE THREAD

**Issue by PanterSoft** [ultralytics/hub#89] opened 2022-08-28 09:06 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

I am trying to upload a Dataset wich has the exact same structure as the tutorial suggests the yaml file has the correct format and the labels only consists of numbers.

<img width="709" alt="Bildschirmfoto 2022-08-28 um 09 27 27" src="https://user-images.githubusercontent.com/96704103/187063004-b60fc36c-74bd-444c-897f-6181692631cf.png">

After that was not working I tried the example dataset coco6 and got the same result shown in the image below.

<img width="1254" alt="Bildschirmfoto 2022-08-28 um 09 20 54" src="https://user-images.githubusercontent.com/96704103/187062696-3201adda-95d9-4427-886a-17212f4d4cdd.png">

### Environment

I am using a 2021 MacBook Pro 14 inch M1 Pro running Safari.

### Minimal Reproducible Example

1. Login
2. Create Dataset
3. Name Dataset and upload dataset.zip
4. Let it upload and fail while processing

**Comment by nicomattes** [comment] 2022-08-28 21:13
I found the issue myself it was some kind of charset issue issue can be closed.

**Comment by glenn-jocher** [comment] 2022-08-29 00:10
@PanterSoft hi I saw this issue was resolved on your side? Should we close the issue?

**Comment by nicomattes** [comment] 2022-08-29 04:42
> @PanterSoft hi I saw this issue was resolved on your side? Should we close the issue?

Sorry was a mistake I still have the same problem.

**Comment by nicomattes** [comment] 2022-08-29 15:44
I found the issue when you create a zip file on MacOS it creates a hidden folder in the file which contains the same files which denn gives the error multiple yaml files. solved it by uploading dataset from Windows

**Comment by kalenmike** [comment] 2022-09-01 14:10
@nicomattes Thanks for letting us know. We will look into improving this for zips created with MacOS.

**Closed by kalenmike** 2022-09-01 14:10 UTC
Labels: bug

**Comment by mehlkelm** [comment] 2022-10-17 08:31
I have the same problem.
Workaround: zip the folder from the command line like this:
https://apple.stackexchange.com/a/239587

**Comment by mehlkelm** [comment] 2022-10-17 13:29
The issue arises (I think) because macOS creates a hidden (for mac users) directory "__MACOSX" inside the zip file that contains additional information about all the files. To a non-mac OS it looks like everything is duplicated.

Maybe the dataset upload tool should just ignore the __MACOSX folder in there.

**Comment by glenn-jocher** [comment] 2022-10-17 13:32
@mehlkelm yeah good point. We definitely want a macOS-robust tool. Could you upload a small zip that's crashing HUB here or email it to glenn.jocher@ultralytics.com? Thanks!

**Comment by mehlkelm** [comment] 2022-10-18 08:39
This is a completely made up example but it shows the problem.
(It doesn't crash HUB, it just shows the "Multiple YAML's found" problem)

[macos_zip_problem_demo.zip](https://github.com/ultralytics/hub/files/9808500/macos_zip_problem_demo.zip)

**Comment by glenn-jocher** [comment] 2022-10-18 12:13
@mehlkelm thanks! We'll use the zip to debug and improve the dataset upload process.

**Comment by glenn-jocher** [comment] 2022-10-18 12:35
When unzipping I see the `__MACOSX/` directory containing a duplicate YAML:
```bash
(venv39) glennjocher@Glenns-MacBook-Air Downloads % unzip macos_zip_problem_demo.zip
Archive:  macos_zip_problem_demo.zip
   creating: macos_zip_problem_demo/
  inflating: macos_zip_problem_demo/.DS_Store  
  inflating: __MACOSX/macos_zip_problem_demo/._.DS_Store  
   creating: macos_zip_problem_demo/images/
  inflating: macos_zip_problem_demo/macos_zip_problem_demo.yaml  
  inflating: __MACOSX/macos_zip_problem_demo/._macos_zip_problem_demo.yaml  
   creating: macos_zip_problem_demo/labels/
  inflating: macos_zip_problem_demo/images/.DS_Store  
  inflating: __MACOSX/macos_zip_problem_demo/images/._.DS_Store  
   creating: macos_zip_problem_demo/images/train/
   creating: macos_zip_problem_demo/images/val/
  inflating: macos_zip_problem_demo/labels/.DS_Store  
  inflating: __MACOSX/macos_zip_problem_demo/labels/._.DS_Store  
   creating: macos_zip_problem_demo/labels/train/
   creating: macos_zip_problem_demo/labels/val/
  inflating: macos_zip_problem_demo/images/train/IMG_1931.jpeg  
  inflating: __MACOSX/macos_zip_problem_demo/images/train/._IMG_1931.jpeg  
  inflating: macos_zip_problem_demo/images/train/IMG_1925.jpeg  
  inflating: __MACOSX/macos_zip_problem_demo/images/train/._IMG_1925.jpeg  
  inflating: macos_zip_problem_demo/images/train/IMG_1923.jpeg  
  inflating: __MACOSX/macos_zip_problem_demo/images/train/._IMG_1923.jpeg  
  inflating: macos_zip_problem_demo/images/train/IMG_1915.jpeg  
  inflating: __MACOSX/macos_zip_problem_demo/images/train/._IMG_1915.jpeg  
  inflating: macos_zip_problem_demo/images/val/IMG_1927.jpeg  
  inflating: __MACOSX/macos_zip_problem_demo/images/val/._IMG_1927.jpeg  
  inflating: macos_zip_problem_demo/images/val/IMG_1914.jpeg  
  inflating: __MACOSX/macos_zip_problem_demo/images/val/._IMG_1914.jpeg  
  inflating: macos_zip_problem_demo/labels/train/IMG_1915.txt  
  inflating: __MACOSX/macos_zip_problem_demo/labels/train/._IMG_1915.txt  
  inflating: macos_zip_problem_demo/labels/train/IMG_1923.txt  
  inflating: __MACOSX/macos_zip_problem_demo/labels/train/._IMG_1923.txt  
  inflating: macos_zip_problem_demo/labels/train/IMG_1925.txt  
  inflating: __MACOSX/macos_zip_problem_demo/labels/train/._IMG_1925.txt  
  inflating: macos_zip_problem_demo/labels/train/IMG_1931.txt  
  inflating: __MACOSX/macos_zip_problem_demo/labels/train/._IMG_1931.txt  
  inflating: macos_zip_problem_demo/labels/val/IMG_1914.txt  
  inflating: __MACOSX/macos_zip_problem_demo/labels/val/._IMG_1914.txt  
  inflating: macos_zip_problem_demo/labels/val/IMG_1927.txt  
  inflating: __MACOSX/macos_zip_problem_demo/labels/val/._IMG_1927.txt  

```

**Comment by mehlkelm** [comment] 2022-10-18 12:40
All the files in __MACOSX are hidden, as are the .DS_Store files, which are also some sort of OS specific info files. Maybe ignoring hidden files in general would be enough…

**Comment by mehlkelm** [comment] 2022-10-18 12:42
(according to the unix way of treating files with names starting with a dot as hidden)

**Comment by glenn-jocher** [comment] 2022-10-18 12:43
@mehlkelm actually this is really strange, on my mac if I unzip using the GUI/mouse commands everything unzips correctly into 1 directory. If I unzip using the terminal I get two top level directories:

```
(venv39) glennjocher@Glenns-MacBook-Air sandbox % unzip macos_zip_problem_demo.zip
```

<img width="917" alt="Screenshot 2022-10-18 at 14 42 08" src="https://user-images.githubusercontent.com/26833433/196432519-85fb9266-2ec0-4856-8c7a-09fcff500401.png">

**Comment by mehlkelm** [comment] 2022-10-18 12:49
I guess the regular mac unzip processes the information in __MACOSX (technically they are resource forks) and doesn't interpret them as files, while all the non Mac tools/OS (even unzip in the terminal on mac?) think they are files.

**Comment by mehlkelm** [comment] 2022-10-18 12:50
but yes, it's silly that the mac puts them there

**Comment by glenn-jocher** [comment] 2022-10-18 13:20
@kalenmike I'm not able to produce any errors with HUBDatasetStats on this zip. To reproduce I downloaded https://github.com/ultralytics/hub/files/9808500/macos_zip_problem_demo.zip, placed in a sandbox/ dir, and ran the code below. 

```python
        from utils.dataloaders import HUBDatasetStats
        stats = HUBDatasetStats('/Users/glennjocher/Downloads/sandbox/macos_zip_problem_demo.zip')  # usage 2
        stats.get_json()
        stats.process_images()
```

<img width="1300" alt="Screenshot 2022-10-18 at 15 17 00" src="https://user-images.githubusercontent.com/26833433/196440558-d5088303-d584-42a4-8d09-c48712033e5a.png">

Initially directory contained only zip:
<img width="857" alt="Screenshot 2022-10-18 at 15 15 52" src="https://user-images.githubusercontent.com/26833433/196440790-de7f1a67-5b68-4b13-98fd-b49857ff3c13.png">

After unzip contained the unzipped dir plus an extra __MAXOSX dir with duplicated data:
<img width="857" alt="Screenshot 2022-10-18 at 15 18 10" src="https://user-images.githubusercontent.com/26833433/196440762-b0539764-c987-4f0b-84d0-db2fecebe044.png">

But the actual dataset processing seemed to work without any duplicate YAML errors. Could you check HUB to see if the error is produced downstream of these steps?

**Comment by glenn-jocher** [comment] 2022-10-18 14:02
@kalenmike @mehlkelm I've opened https://github.com/ultralytics/yolov5/pull/9843 in YOLOv5 to better handle unzipping while rejecting files in an exclude list, i.e. .DS_Store and __MACOSX instances in file paths.

**Comment by kalenmike** [comment] 2022-10-18 14:05
@glenn-jocher There is independent validation on the server that is not excluding the MACOSX folder by the looks of it.

**Comment by glenn-jocher** [comment] 2022-10-18 19:56
@kalenmike ok got it, I'll let you try to debug on the server side.

**Comment by kalenmike** [comment] 2022-10-20 11:53
This is now resolved and zip files created on Mac can now be processed successfully without special zipping.
