### ISSUE TITLE
Problems when training model

### ISSUE THREAD

**Issue by wagnercorreiadextak** [ultralytics/hub#905] opened 2024-10-28 12:05 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

Hello, every time I try to train a model with your video cards, the loader keeps running the training without happening.

### Environment

Web

### Minimal Reproducible Example

model training

**Comment by UltralyticsAssistant** [comment] 2024-10-28 12:05
👋 Hello @wagnercorreiadextak, thank you for bringing this issue to our attention about [Ultralytics HUB](https://github.com/ultralytics/hub) 🚀!

Please visit our [HUB Docs](https://docs.ultralytics.com/hub) for detailed guidance across various components:

- [**Quickstart**](https://docs.ultralytics.com/hub/quickstart). Begin training and deploying YOLO models with HUB quickly.
- [**Datasets: Preparing and Uploading**](https://docs.ultralytics.com/hub/datasets). Instructions on preparing and uploading datasets to HUB in YOLO format.
- [**Projects: Creating and Managing**](https://docs.ultralytics.com/hub/projects). Enhance your project management by grouping models effectively.
- [**Models: Training and Exporting**](https://docs.ultralytics.com/hub/models). Train YOLOv5 and YOLOv8 models and export them for deployment.
- [**Integrations**](https://docs.ultralytics.com/hub/integrations). Discover integration options for TensorFlow, ONNX, and more.
- [**Ultralytics HUB App**](https://docs.ultralytics.com/hub/app). Use the Ultralytics App on iOS and Android to run models on mobile devices.
    * [**iOS**](https://docs.ultralytics.com/hub/app/ios). Optimize YOLO CoreML models on Apple's devices.
    * [**Android**](https://docs.ultralytics.com/hub/app/android). Utilize TFLite acceleration on Android devices.
- [**Inference API**](https://docs.ultralytics.com/hub/inference-api). Use the API to generate predictions with cloud-based models.

Since this seems like a 🐛 Bug Report, could you please provide more details, such as screenshots and precise steps on how to [reproduce](https://docs.ultralytics.com/help/minimum_reproducible_example/) this issue to help us investigate it further?

This is an automated response to ensure you have the right resources. An Ultralytics engineer will review this issue and provide more guidance soon. Thanks for your patience! 😊

**Comment by pderrenger** [comment] 2024-11-09 12:20
@wagnercorreiadextak hello! 😊

Thank you for reaching out and letting us know about the issue you're experiencing with model training on Ultralytics HUB. Let's try to get this sorted out for you!

First, please ensure that you're using the latest version of the Ultralytics HUB. Sometimes, updates can resolve unexpected issues. If the problem persists, could you provide a bit more detail? For example, any error messages you might see or specific steps leading up to the issue. This information can help us diagnose the problem more effectively.

In the meantime, you might want to try using an alternative training method, such as Google Colab or bringing your own agent, to see if the issue is specific to the current setup. You can find more details on these options in the [Ultralytics HUB documentation](https://docs.ultralytics.com/hub/models/).

If you continue to face issues, please feel free to update this thread with any additional information. We're here to help! 🚀

Thank you for your patience and for being part of the Ultralytics community!

**Comment by yogendrasinghx** [comment] 2024-11-12 12:50
Hi @wagnercorreiadextak,

Could you please share more details about your training setup? Specifically, are you using cloud training, Google Colab, or training with your own custom agent? This information will help us better understand the issue. Additionally, if you can share some screenshots or any error messages you’re seeing, that would be very helpful for diagnosing the problem.

Thank you for your patience, and we look forward to assisting you further!

**Comment by wagnercorreiadextak** [comment] 2024-11-12 12:54
Hello, I am training using Ultralytics HUB GPUs. I use the standard 100-epoch training recommended by the platform. At some point, any GPU I select fails to start training.

**Comment by yogendrasinghx** [comment] 2024-11-12 12:59
@wagnercorreiadextak Thank you for sharing the details, and we apologize for the inconvenience. We had some known issues with Ultralytics cloud training a few days ago, but it's fixed now. Please try training your model again, and let us know if you encounter any further issues.

**Closed** 2024-12-04 10:14 UTC
Labels: bug, HUB
