### ISSUE TITLE
Training of a yolov11 model always get disconnected

### ISSUE THREAD

**Issue by marek-szanyi** [ultralytics/hub#943] opened 2024-12-05 13:43 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

No matter which GPU card I select for training it always ends with a message that it was disconnected. After restarting the training it spends a whole lot of time preparing the cloud instance and after that after a short while it shows the disconnect message. Thisway I'm burning all my credit for computation on the initialization phase.

### Environment

Ultralytics HUB Version
v0.1.77
Client User Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Operating System
Win32
Browser Window Size
2560 x 1279
Server Timestamp
1733405296

### Minimal Reproducible Example

1. Open a dataset from Roboflow.com
2. Select yolov11 as the pretrained model 
3. Set the image scale to 1280
4. Start the training

**Comment by UltralyticsAssistant** [comment] 2024-12-05 13:43
👋 Hello @marek-szanyi, thank you for raising an issue about [Ultralytics HUB](https://hub.ultralytics.com) 🚀! Please visit our [HUB Docs](https://docs.ultralytics.com/hub) to learn more:

- [**Quickstart**](https://docs.ultralytics.com/hub/quickstart). Start training and deploying YOLO models with HUB in seconds.
- [**Datasets: Preparing and Uploading**](https://docs.ultralytics.com/hub/datasets). Learn how to prepare and upload your datasets to HUB in YOLO format.
- [**Projects: Creating and Managing**](https://docs.ultralytics.com/hub/projects). Group your models into projects for improved organization.
- [**Models: Training and Exporting**](https://docs.ultralytics.com/hub/models). Train YOLOv5 and YOLOv8 models on your custom datasets and export them to various formats for deployment.
- [**Integrations**](https://docs.ultralytics.com/hub/integrations). Explore different integration options for your trained models, such as TensorFlow, ONNX, OpenVINO, CoreML, and PaddlePaddle.
- [**Ultralytics HUB App**](https://docs.ultralytics.com/hub/app). Learn about the Ultralytics App for iOS and Android, which allows you to run models directly on your mobile device.
    * [**iOS**](https://docs.ultralytics.com/hub/app/ios). Learn about YOLO CoreML models accelerated on Apple's Neural Engine on iPhones and iPads.
    * [**Android**](https://docs.ultralytics.com/hub/app/android). Explore TFLite acceleration on mobile devices.
- [**Inference API**](https://docs.ultralytics.com/hub/inference-api). Understand how to use the Inference API for running your trained models in the cloud to generate predictions.

If this is a 🐛 Bug Report, we kindly ask you to provide more details if possible:
- Could you confirm whether the issue persists with different datasets or model configurations?
- It seems you've outlined some steps, but please ensure it's a detailed [Minimum Reproducible Example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/), including any relevant model settings, logs, or screenshots.

There may also be connectivity or resource management issues during training on cloud instances. While we investigate, ensure your internet connection remains stable and avoid any interruptions in your session.

If this is a ❓ Question, providing additional information such as dataset specifics, exact problem environment, and expected behavior will help guide you better.

An Ultralytics engineer will review your report and assist you shortly. Thank you for your patience and for being part of the Ultralytics community! ✨

**Comment by yogendrasinghx** [comment] 2024-12-05 13:56
@marek-szanyi We sincerely apologize for the inconvenience caused and thank you for reporting this issue.

Let me confirm the issue on our end, and once verified, one of our developers will begin working on resolving the bug.

We truly appreciate your patience, and I’ll keep you updated as we make progress.

**Comment by marek-szanyi** [comment] 2024-12-05 14:41
I think it's the image scale that is causing this issue. Because I have started a new training on the same dataset but this time left with the default image size and so far so good. No training interruptions so far.

**Comment by sjocnjfjd** [comment] 2024-12-06 15:02
100 epochs completed in 0.142 hours.
Optimizer stripped from runs/detect/train/weights/last.pt, 5.5MB
Optimizer stripped from runs/detect/train/weights/best.pt, 5.5MB

Validating runs/detect/train/weights/best.pt...
Ultralytics 8.3.44 🚀 Python-3.10.12 torch-2.5.1+cu121 CUDA:0 (Tesla T4, 15102MiB)
YOLO11n summary (fused): 238 layers, 2,582,347 parameters, 0 gradients, 6.3 GFLOPs
FileNotFoundError Traceback (most recent call last)
<ipython-input-2-92a5d7b00514> in <cell line: 4>()
2
3 model = YOLO('https://hub.ultralytics.com/models/Lcn7iZIH2yxgTClirLcl')
----> 4 results = model.train(data='/datasets/a2O66UeTvAEqSUPPff6l/lane/lane.yaml', project='runs/train', name='exp', epochs=100)

6 frames
/usr/local/lib/python3.10/dist-packages/ultralytics/data/utils.py in check_det_dataset(dataset, autodownload)
327 else:
328 m += f"\nNote dataset download directory is '{DATASETS_DIR}'. You can update this in '{SETTINGS_FILE}'"
--> 329 raise FileNotFoundError(m)
330 t = time.time()
331 r = None # success

FileNotFoundError:
Dataset '/content/datasets/lane/lane.yaml' images not found ⚠️, missing path '/content/datasets/D:python新/建文件夹 (2)/hakusenninnshiki.v2i.yolov11/lane.yaml/images/val'
Note dataset download directory is '/content/datasets'. You can update this in '/root/.config/Ultralytics/settings.json'
why can not I deploy my model into my app
it always show that

**Comment by pderrenger** [comment] 2024-12-07 08:05
@sjocnjfjd it looks like the issue stems from a missing or misconfigured dataset path during training or validation. Let me guide you step by step to resolve this:

### Issue Analysis:
The error message, `FileNotFoundError: Dataset '/content/datasets/lane/lane.yaml' images not found`, indicates that the specified path for your dataset doesn't contain the expected files. Specifically, the dataset's `images/val` folder seems to be mislocated or absent.

### Suggested Fix:
1. **Verify Dataset Path**: 
   - Confirm that the dataset path (`/content/datasets/lane/lane.yaml`) is correct and that the `lane.yaml` file properly references the `train`, `val`, and `test` image folders.
   - Ensure these image folders contain the actual image files and are accessible in your environment.

   Your `lane.yaml` should look something like this:
   ```yaml
   train: /content/datasets/lane/images/train  # Path to training images
   val: /content/datasets/lane/images/val      # Path to validation images

   nc: 5                                       # Number of classes
   names: ['class1', 'class2', 'class3', 'class4', 'class5']  # Class names
   ```

2. **Ensure Dataset Availability**:
   - If you're using a dataset downloaded or linked from an external source (e.g., Roboflow or custom storage), make sure it is correctly placed in `/content/datasets/lane/` and is fully accessible.
   - If the dataset is not found, you may need to re-download it or ensure it's synced properly into the environment (e.g., Google Drive or other storage).

3. **Update Dataset Directory**:
   - If you're using a custom directory for your datasets, you can update the directory setting in:
     ```
     /root/.config/Ultralytics/settings.json
     ```
     Modify the `DATASETS_DIR` to point to the correct dataset base path.

### Deploying Your Model into Your App:
Once the dataset path issue is resolved and training completes successfully, you can deploy the model to your app. Here’s how:
1. Export the trained model with the simplified and deployment-ready format:
   ```bash
   yolo export model=runs/train/exp/weights/best.pt format=torchscript  # or `onnx`/`tflite` for mobile apps.
   ```

2. Use the exported `best.pt` file in your app. For mobile deployment, you can leverage [Ultralytics HUB App](https://docs.ultralytics.com/hub/app/) to run models efficiently:
   - [iOS App](https://docs.ultralytics.com/hub/app/ios)
   - [Android App](https://docs.ultralytics.com/hub/app/android)

### Additional Debugging:
If you're still encountering issues:
   - Ensure you're running the latest version of the necessary libraries:
     ```bash
     pip install ultralytics --upgrade
     ```
   - You can read more about preparing datasets and deployment in the [Ultralytics HUB Dataset Guide](https://docs.ultralytics.com/hub/datasets) and [Ultralytics HUB Models Guide](https://docs.ultralytics.com/hub/models/).

Please verify these steps and share any updates. The YOLO community and Ultralytics team are here to assist! 😊

**Comment by sjocnjfjd** [comment] 2024-12-07 13:40
在 0.142 小时内完成 100 个 epoch。
从 runs/detect/train/weights/last.pt 中剥离的优化器，5.3MB
从 runs/detect/train/weights/best.pt 中剥离的优化器，5.3MB


正在验证 runs/detect/train/weights/best.pt...
Ultralytics 8.3.47 🚀 Python-3.10.12 torch-2.5.1+cu121 CUDA：0 （特斯拉 T4， 15102MiB）
YOLOv5n 摘要（融合）：193 层，2,503,139 个参数，0 个梯度，7.1 GFLOP
---------------------------------------------------------------------------
FileNotFoundError Traceback（最近调用最后）
[<ipython-input-2-1d475651e4d9&gt;]（https://localhost:8080/#） 在 <细胞系：4&gt;（） 中
2
3 模型 = YOLO（'https：//hub.ultralytics.com/models/zyjF4y3ImA2weF6toEh3'）
----&gt; 4 个结果 = model.train（）


6 帧
[/usr/local/lib/python3.10/dist-packages/ultralytics/data/utils.py]（https://localhost:8080/#） in check_det_dataset（数据集， 自动下载）
其他 327 个：
328 m += f“\n注意数据集下载目录为 '{DATASETS_DIR}'。你可以在 '{SETTINGS_FILE}' 中更新它”
--&gt; 329 引发 FileNotFoundError（m）
330 t = 时间
331 r = 无 # 成功


FileNotFoundError 中：
数据集 '/content/datasets/lane/lane.yaml' 图像未找到⚠️，缺少路径 '/content/datasets/D：python新建文件夹 （2）/hakusenninnshiki.v2i.yolov11/lane.yaml/images/val'
注意数据集下载目录为“/content/datasets”。您可以在 '/root/.config/Ultralytics/settings.json' 中更新此内容
为什么仍然找不到它，但我使用您现有的数据集成功了？

**Comment by pderrenger** [comment] 2024-12-08 02:42
感谢您提供详细的错误报告！根据您的描述，这个问题似乎与数据集路径配置缺失或不正确有关。以下是可能的原因和解决方法：

---

### 问题分析
1. **缺少数据路径**：
   文件路径 `/content/datasets/D:python新建文件夹（2）/hakusenninnshiki.v2i.yolov11/lane.yaml/images/val` 不存在或没有正确配置数据。
   
2. **路径格式问题（特殊字符）**：
   路径中可能存在非标准字符（如“新建文件夹”）或错误的路径分隔符，可能导致系统无法正确识别。

3. **数据集配置文件（`lane.yaml`）有误**：
   YAML 文件中用于定位 `train` 和 `val` 图片的路径未正确指向数据集所在的目录。

---

### 解决方案
#### 1. **检查数据集文件系统**：
   确保 `/content/datasets` 目录中存在以下结构：
   ```
   datasets/
   ├── lane/
       ├── images/
           ├── train/
           ├── val/
       ├── labels/
           ├── train/
           ├── val/
   ```

#### 2. **验证 `lane.yaml` 的配置**
   请确保 `lane.yaml` 文件中路径描述如下，并与数据存储位置匹配：
   ```yaml
   train: /content/datasets/lane/images/train  # 训练图片路径
   val: /content/datasets/lane/images/val      # 验证图片路径

   nc: 2                                       # 类别数量
   names: ['class1', 'class2']                 # 类别名称
   ```

#### 3. **避免使用特殊字符路径**
   如果路径中包含中文或特殊字符，请将数据移动至路径命名更简单的目录，如 `/content/datasets/lane/`。

#### 4. **更新数据集目录配置**：
   如果数据已经下载到其他位置，可以编辑：
   ```
   /root/.config/Ultralytics/settings.json
   ```
   将 `DATASETS_DIR` 指向新的数据集根目录。

---

### 额外建议
如果您已验证路径正确而问题依旧存在，可以通过以下步骤重新加载模型和数据：
```python
from ultralytics import YOLO

model = YOLO("path/to/your/model.pt")  # 加载模型路径
# 使用正确的路径启动训练
results = model.train(data="path/to/lane.yaml", epochs=100, imgsz=640)
```

---

### Ultralytics HUB 的支持
若您仍有疑问或想更便捷地使用云功能，建议上传数据集至 [Ultralytics HUB](https://hub.ultralytics.com) 并直接通过平台进行训练和管理数据。此外，您可以利用平台的导入功能自动处理数据集路径问题。

尝试以上建议后仍存在问题，请随时分享更多日志，我们乐意为您继续排查！💡

**Comment by marek-szanyi** [comment] 2024-12-12 11:14
> @sjocnjfjd it looks like the issue stems from a missing or misconfigured dataset path during training or validation. Let me guide you step by step to resolve this:
> 
> ### Issue Analysis:
> The error message, `FileNotFoundError: Dataset '/content/datasets/lane/lane.yaml' images not found`, indicates that the specified path for your dataset doesn't contain the expected files. Specifically, the dataset's `images/val` folder seems to be mislocated or absent.
> 
> ### Suggested Fix:
> 1. **Verify Dataset Path**:
>    
>    * Confirm that the dataset path (`/content/datasets/lane/lane.yaml`) is correct and that the `lane.yaml` file properly references the `train`, `val`, and `test` image folders.
>    * Ensure these image folders contain the actual image files and are accessible in your environment.
>    
>    Your `lane.yaml` should look something like this:
>    ```yaml
>    train: /content/datasets/lane/images/train  # Path to training images
>    val: /content/datasets/lane/images/val      # Path to validation images
>    
>    nc: 5                                       # Number of classes
>    names: ['class1', 'class2', 'class3', 'class4', 'class5']  # Class names
>    ```
> 2. **Ensure Dataset Availability**:
>    
>    * If you're using a dataset downloaded or linked from an external source (e.g., Roboflow or custom storage), make sure it is correctly placed in `/content/datasets/lane/` and is fully accessible.
>    * If the dataset is not found, you may need to re-download it or ensure it's synced properly into the environment (e.g., Google Drive or other storage).
> 3. **Update Dataset Directory**:
>    
>    * If you're using a custom directory for your datasets, you can update the directory setting in:
>      ```
>      /root/.config/Ultralytics/settings.json
>      ```
>      
>      
>          
>            
>          
>      
>            
>          
>      
>          
>        
>      Modify the `DATASETS_DIR` to point to the correct dataset base path.
> 
> ### Deploying Your Model into Your App:
> Once the dataset path issue is resolved and training completes successfully, you can deploy the model to your app. Here’s how:
> 
> 1. Export the trained model with the simplified and deployment-ready format:
>    ```shell
>    yolo export model=runs/train/exp/weights/best.pt format=torchscript  # or `onnx`/`tflite` for mobile apps.
>    ```
> 2. Use the exported `best.pt` file in your app. For mobile deployment, you can leverage [Ultralytics HUB App](https://docs.ultralytics.com/hub/app/) to run models efficiently:
>    
>    * [iOS App](https://docs.ultralytics.com/hub/app/ios)
>    * [Android App](https://docs.ultralytics.com/hub/app/android)
> 
> ### Additional Debugging:
> If you're still encountering issues:
> 
> * Ensure you're running the latest version of the necessary libraries:
>   ```shell
>   pip install ultralytics --upgrade
>   ```
> * You can read more about preparing datasets and deployment in the [Ultralytics HUB Dataset Guide](https://docs.ultralytics.com/hub/datasets) and [Ultralytics HUB Models Guide](https://docs.ultralytics.com/hub/models/).
> 
> Please verify these steps and share any updates. The YOLO community and Ultralytics team are here to assist! 😊

How Am I supposed to do all that if I am exporting the the dataset from roboflow.com ? Your UI does not give me the option to do anything from what you have suggested. I would expect you to either fix the import. If the dataset is wrong in the first place the import should fail as well. Or change your UI so a user can perform all those steps you have just written. Thanks

**Comment by yogendrasinghx** [comment] 2024-12-12 11:59
Hi @marek-szanyi,

We’ve tried reproducing the issue on our end using a Roboflow dataset with both the 1280 image size and the default settings, but so far we haven’t encountered any problems.

To help us investigate further, could you please share your Model ID? You can find it in the URL when accessing the model in the HUB Web, for example: https://hub.ultralytics.com/models/7wzkDSKNMcwkPTs8ZVJC.

`Model ID: 7wzkDSKNMcwkPTs8ZVJC`

Providing the Model ID will allow us to locate your account and gain a better understanding of the issue. We sincerely apologize for any inconvenience this has caused and appreciate your patience as we work on a resolution.

Looking forward to your response.

**Comment by marek-szanyi** [comment] 2024-12-12 17:53
Hi, 

The model I was trying to train : https://hub.ultralytics.com/models/nnU0F5lrqbBbP86tywIZ 
I was using this dataset: https://universe.roboflow.com/egor-40xaz/carts-inxbs (On the roboflow page I have selected the option to export it directly to your hub)

**Comment by yogendrasinghx** [comment] 2024-12-12 21:07
Hi @marek-szanyi,

Thanks for providing the Model ID and the Roboflow dataset URL. I tried training a model using the same dataset with a custom image size of `1280`, and it worked without any issues, as shown in the screenshot below.

<img width="1506" alt="image" src="https://github.com/user-attachments/assets/fc4954dd-20fb-4057-9e70-778dc5e59404" />


I’ve also located the model `7wzkDSKNMcwkPTs8ZVJC` on your account and can confirm that a 5-epoch training run was successfully completed, indicating that we do have a valid checkpoint from those epochs.

It appears that your account currently shows a negative wallet balance. This could be causing the training sessions to disconnect prematurely. Please consider topping up your account and then try running the training again. If you continue to experience issues after that, feel free to reach out and we’ll be happy to help troubleshoot further.

**Closed by yogendrasinghx** 2024-12-12 21:07 UTC
Labels: bug, non-reproducible, HUB, info needed, web
