### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by vincentpahayahay** [ultralytics/hub#896] opened 2024-10-22 16:13 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

I created project in website and then try to preview it in Android, the model didn't appear in mobile app. 

### Environment

Yolo11n in Android

### Minimal Reproducible Example

1. Sign up to ultralytics app through gmail
2. Select model
3. Example yolov8n
4. Preview
5. Preview in Android
6. Open Android app
7. Sign in using the same gmail
8. No model displayed at all. (Fix this in Android) 

### Additional

That's all

**Comment by UltralyticsAssistant** [comment] 2024-10-22 16:13
👋 Hello @vincentpahayahay, thank you for reporting this issue about the [ultralytics/hub](https://github.com/ultralytics/hub) repository! 🚀 We're sorry to hear you're experiencing this problem with the Android app.

To help us resolve this 🐛 bug as quickly as possible, please ensure you've provided a complete [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/), including precise steps and screenshots if applicable. Here are some additional resources that might be useful:

- [**Ultralytics HUB Docs**](https://docs.ultralytics.com/hub): Get detailed information on using HUB effectively.
- [**Models: Training and Exporting**](https://docs.ultralytics.com/hub/models): Learn how to train YOLO models and manage them.
- [**Ultralytics HUB App**](https://docs.ultralytics.com/hub/app): Get insights into the mobile app features.
    * [**Android**](https://docs.ultralytics.com/hub/app/android): Explore TFLite acceleration and other functionalities on Android devices.

An Ultralytics engineer will review your report and get back to you soon. Thank you for your patience and for helping us improve our services! 😊🔧

**Comment by vincentpahayahay** [comment] 2024-10-22 16:15
1. Sign up to ultralytics hub in web through gmail

**Comment by pderrenger** [comment] 2024-10-23 01:28
Hello! 😊

Thank you for reaching out. It seems like you're having trouble with the Android app not displaying your model. Here are a few steps you can try to resolve this issue:

1. **Ensure Latest Version**: Make sure both the Ultralytics HUB web and Android app are updated to the latest versions. This can often resolve unexpected issues.

2. **Check Synchronization**: After signing in on the Android app, give it a moment to sync with your account. Sometimes, it might take a little time for the models to appear.

3. **Network Connection**: Verify that your device has a stable internet connection, as this is necessary for syncing data between the web and mobile app.

4. **Re-login**: Try logging out and back into the Android app to refresh your session.

If the issue persists, please let us know, and we’ll be happy to assist further. Your feedback is invaluable in helping us improve our services. Thank you for your patience and support! 🚀

Feel free to check out the [Ultralytics HUB Docs](https://docs.ultralytics.com/hub/app/) for more detailed guidance.

**Comment by yogendrasinghx** [comment] 2024-10-25 11:49
@vincentpahayahay Thank you for reporting this issue and providing detailed steps to reproduce it. We’re aware of the issue with models not appearing in the Android app, and I'm pleased to inform you that we have addressed this in our upcoming app release. This update, which includes a fix for this specific issue, will be available later this week.

We appreciate your patience and feedback as it helps us improve. Thank you again for reaching out, and please don't hesitate to let us know if you encounter any further issues.

**Closed** 2024-10-30 12:45 UTC
Labels: bug

**Comment by vincentpahayahay** [comment] 2024-10-30 13:15
It is already working, thank you for fast update it will help a lot in our
project.

**Comment by vincentpahayahay** [comment] 2024-11-02 05:12
Another problem, I trained a model from ultralytics hub and then I exported
in on Android App which is the ultralytics hub app, it appear in the app
but I cannot use the model because I can't download it. It is stucked in
"loading" In the camera part. I couldn't load the model. Try to do this:

1. Train a model from ultralytics hub web
2. Export to Android
3. Log in to Android app (ultralytics hub)
4. Download the model that you have trained. (The error is here, couldn't
download the model)

**Comment by pderrenger** [comment] 2024-11-03 01:49
Hello! Thank you for bringing this to our attention. It sounds like you're encountering an issue with downloading the model on the Android app. Let's try a few steps to resolve this:

1. **Update the App**: Ensure that you have the latest version of the Ultralytics HUB app installed on your Android device. Updates often include important bug fixes and improvements.

2. **Check Internet Connection**: A stable internet connection is crucial for downloading models. Please verify that your device is connected to a reliable network.

3. **Clear Cache**: Sometimes, clearing the app's cache can resolve loading issues. You can do this by going to your device's settings, finding the Ultralytics app, and selecting "Clear Cache."

4. **Re-login**: Try logging out of the app and then logging back in. This can refresh your session and potentially resolve any syncing issues.

5. **Reproduce the Issue**: If the problem persists, please try to reproduce the issue with the latest app version and let us know if it continues. This will help us investigate further.

We appreciate your patience and cooperation as we work to improve the app experience. If you have any more questions or need further assistance, feel free to reach out. Thank you for being a part of the Ultralytics community! 😊

**Comment by vincentpahayahay** [comment] 2024-11-03 02:31
I am already using the latest version of the app, I have done everything
like logout and then log in then download the model, I also clear the cache
then login then download na model, I also clear the data then login then
download the model I also uninstall then install again the app. All of them
did not work, I have stable internet connection.

**Comment by pderrenger** [comment] 2024-11-03 09:42
Hello! 😊

Thank you for your detailed response and for trying those troubleshooting steps. Since you've already ensured that everything is up to date and have a stable internet connection, let's explore a few more possibilities:

1. **Device Compatibility**: Double-check if your device meets the necessary requirements for running the Ultralytics HUB app. Some older devices might face compatibility issues.

2. **Storage Space**: Ensure that your device has enough storage space available for downloading and running the model. Insufficient storage can sometimes cause download issues.

3. **Error Logs**: If possible, check if there are any error messages or logs within the app that might provide more insight into what's happening during the download process.

4. **Alternative Device**: If you have access to another Android device, try logging in and downloading the model there to see if the issue persists. This can help determine if the problem is device-specific.

5. **Contact Support**: Since you've already tried multiple solutions, it might be helpful to reach out to our support team through the [Ultralytics GitHub Issues](https://github.com/ultralytics/hub/issues) page with any error logs or additional details. This will allow us to investigate further and provide a more tailored solution.

We appreciate your patience and understanding as we work to resolve this issue. Thank you for being a valued member of the Ultralytics community! 🚀

**Comment by vincentpahayahay** [comment] 2024-11-03 10:09
I am using Tecno Camon 20s Pro 5g, CPU Dimensity 8020, 16gb Ram, Android
version 14, 256gb storage and the used storage is only 90gb. With this
specs I think the app is compatible, kindly address the issue because this
app is a big help for me if it is all working properly. Thank you

**Comment by pderrenger** [comment] 2024-11-03 19:47
Hello! 😊

Thank you for providing your device specifications. With such robust specs, your Tecno Camon 20s Pro 5G should indeed be compatible with the Ultralytics HUB app. Let's try to address the issue further:

1. **Reproducibility**: Please ensure that the issue is reproducible with the latest version of the app. Sometimes, updates can resolve unexpected bugs.

2. **Error Messages**: If you encounter any specific error messages or logs during the download process, sharing those details can be incredibly helpful for diagnosing the issue.

3. **App Permissions**: Double-check that the app has all the necessary permissions enabled on your device, especially for storage and network access.

4. **Device Settings**: Ensure that there are no restrictions on background data usage or battery optimization settings that might interfere with the app's functionality.

5. **Community Support**: While we can't offer private support, the Ultralytics community on GitHub is a great resource. Feel free to share any additional details there, and our team will continue to assist you.

We appreciate your patience and understanding as we work to resolve this issue. Your feedback is invaluable in helping us improve the app experience. Thank you for being a part of the Ultralytics community! 🚀
