### ISSUE TITLE
This account is currently being deleted.

### ISSUE THREAD

**Issue by maxmistral** [ultralytics/hub#947] opened 2024-12-09 00:44 UTC
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

Hello there,

I encountered an issue while attempting to connect to my Ultralytics Hub account. The website displayed the following message:

    "This account is currently being deleted."

From what I recall, I still have credits available on my account. Moreover, I never asked for my account to be deleted. Could you please clarify why this is happening and help resolve the issue?

I'm available in DM if need the email associed to my account, this is also the email associated with this Github account, even though I didn't sign up with GitHub.

Thank you for your assistance!

### Minimal Reproducible Example

Login to Hub with email + password or Google
Error pop in JS MessageBox

**Comment by UltralyticsAssistant** [comment] 2024-12-09 00:45
👋 Hello @maxmistral, thank you for raising an issue about [Ultralytics HUB](https://hub.ultralytics.com) 🚀! Please visit our [HUB Docs](https://docs.ultralytics.com/hub) to learn more:

- [**Quickstart**](https://docs.ultralytics.com/hub/quickstart). Start training and deploying YOLO models with HUB in seconds.
- [**Datasets: Preparing and Uploading**](https://docs.ultralytics.com/hub/datasets). Learn how to prepare and upload your datasets to HUB in YOLO format.
- [**Projects: Creating and Managing**](https://docs.ultralytics.com/hub/projects). Group your models into projects for improved organization.
- [**Models: Training and Exporting**](https://docs.ultralytics.com/hub/models). Train YOLOv5 and YOLOv8 models on your custom datasets and export them to various formats for deployment.
- [**Integrations**](https://docs.ultralytics.com/hub/integrations). Explore different integration options for your trained models, such as TensorFlow, ONNX, OpenVINO, CoreML, and PaddlePaddle.
- [**Ultralytics HUB App**](https://docs.ultralytics.com/hub/app). Learn about the Ultralytics App for iOS and Android, which allows you to run models directly on your mobile device.
   * [**iOS**](https://docs.ultralytics.com/hub/app/ios). Learn about YOLO CoreML models accelerated on Apple's Neural Engine on iPhones and iPads.
   * [**Android**](https://docs.ultralytics.com/hub/app/android). Explore TFLite acceleration on mobile devices.
- [**Inference API**](https://docs.ultralytics.com/hub/inference-api). Understand how to use the Inference API for running your trained models in the cloud to generate predictions.

If this is a 🐛 Bug Report, please provide screenshots, error logs, and steps to reproduce your issue. For example, you mentioned: 
> Minimal Reproducible Example: Login to Hub with email + password or Google  
> Error pop in JS MessageBox  

Expanding on this, please confirm the exact steps you followed, including the browser and device you are using. Providing a [Minimal Reproducible Example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/) will help us investigate the issue more effectively. If you can, please share a screenshot of the error message you encounter.

If this is a ❓ Question, feel free to add any environment details or specific context that might help clarify your problem (e.g., the browser/type of device, or any steps you've tried so far).

A member of our team will review this shortly 👨‍💻. This is an automated response to ensure we capture all relevant information about your issue, but rest assured, an Ultralytics engineer will assist you personally as soon as possible. Thank you for your patience! 😊

**Comment by pderrenger** [comment] 2024-12-09 07:27
@maxmistral hello,

Thank you for reporting this issue, and I’m sorry to hear about the trouble you’re facing with your Ultralytics HUB account.

The message `This account is currently being deleted` typically appears if there was a deletion request initiated, either intentionally or accidentally. However, since you mentioned you didn’t request this and still have credits, this might be an unexpected issue.

To resolve this, please try the following steps:
1. **Clear Cache and Cookies:** Sometimes, browser cache or cookies can cause login issues. Clear them and attempt to log in again.
2. **Retry Login:** Ensure you’re using the correct login method (email/password or Google) associated with your account.
3. **Contact Support:** Since your account might require manual intervention, please reach out to our support team by submitting the issue via the [Ultralytics HUB Support Page](https://hub.ultralytics.com/support). Provide details such as:
   - The exact email associated with the account.
   - A description of the issue (you can reference this GitHub report for context).
   - Any additional information that might help identify your account.

Unfortunately, we cannot handle account-specific issues like this over GitHub for privacy and security reasons. Rest assured, our team will prioritize resolving this for you once the details are received.

If you continue to face issues or need further assistance, feel free to update this thread or use our [GitHub Issues](https://github.com/ultralytics/hub/issues/new/choose) page for general inquiries.

Thank you for your patience, and we’ll ensure this gets resolved for you promptly.

**Comment by sergiuwaxmann** [comment] 2024-12-09 08:45
@maxmistral Can you please share you email address?

**Comment by maxmistral** [comment] 2024-12-09 09:26
maxmistral.polo@gmail.com
> @maxmistral Can you please share you email address?

**Closed** 2024-12-09 09:32 UTC
Labels: bug, HUB
